### ISSUE TITLE
Missing MAINTAINERS file

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker-bench-security#107]
I'm working on preparing the open source repositories for the new centralized maintainers file, but noticed this repository does not yet have a MAINTAINERS file.

I can create a PR to fix this, but I'm not sure who should be included as maintainer(s).

@konstruktoid @diogomonica are you the maintainers, of this project, or should I add other people here?

for reference, see docker/opensource#35 and docker/docker#18321

**Comment by konstruktoid** [comment]
I guess me and @diogomonica are the mantainers, so it looks good to me.
