### ISSUE TITLE
Recently added use of systemctl to get systemd file path is not working on centos7

### ISSUE THREAD

**Issue by gmanfunky** [docker/docker-bench-security#109]
related to this merge a couple weeks ago: https://github.com/docker/docker-bench-security/pull/102

Running the benchmark script inside a Centos7 container on the centos host returns a few of these in section 3:

```Failed to get D-Bus connection: No connection to service manager.```

It looks like the running benchmark container is missing access to some socket or another that systemctl wants.

But simple adding ```-v  /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket``` Did not resolve this. 

Maybe the benchmark should go back to the hard coded file-path, unless @konstruktoid has a really good reason not to?

**Comment by konstruktoid** [comment]
Thanks for reporting this @gmanfunky and I'll have a check with the Centos container as well.
Can you post the result of `systemctl show -p FragmentPath docker-registry.service` and `systemctl show -p FragmentPath docker.service` on your Centos host and pref from inside a Centos container.

**Comment by konstruktoid** [comment]
Please have a look at https://github.com/tutumcloud/tutum-centos/issues/6

**Comment by konstruktoid** [comment]
Please have a look at https://github.com/docker/docker-bench-security/pull/110

**Comment by gmanfunky** [comment]
https://github.com/docker/docker-bench-security/pull/110 runs fine for me and will address this issue but currently doesn't account for a case when systemctl doesn't work right inside a container and the host has a systemd override file in /etc/systemd/system.
