### ISSUE TITLE
How to run this against a swarm?

### ISSUE THREAD

**Issue by schmunk42** [docker/docker-bench-security#113]
Since the default commands provided are using host-volumes I asked myself, if there is any advice how to run this against a swarm or is docker-bench-security intended to run on every host of a swarm?

**Comment by konstruktoid** [comment]
Hi @schmunk42, I'm not aware of any advice or anyone using docker-bench-security against a swarm, and the design of docker-bench-security has been focused on running it on a single docker host.

**Comment by schmunk42** [comment]
Thanks, I guess that's fine - was just curious.
