### ISSUE TITLE
Conflict of tool and goal?

### ISSUE THREAD

**Issue by jianghaitao** [docker/docker-bench-security#119]
We definitely need something like this tool to ensure Docker deployment is secure. However, it seems to me that we might have a conflict of the tool and goal here. The tool runs with lots of privileges, but a reasonably secured deployment of Docker daemon will prohibit that, e.g. host network. 

For an example, when I turn on the user namespace in Docker 1.10, I can not run the tool as a container
```
docker run -it --net host --pid host --cap-add audit_control     -v /var/lib:/var/lib     -v /var/run/docker.sock:/var/run/docker.sock     -v /usr/lib/systemd:/usr/lib/systemd     -v /etc:/etc --label docker_bench_security     docker/docker-bench-security
docker: Error response from daemon: Cannot share the host or a container's network namespace when user namespaces are enabled..
See 'docker run --help'.
```
Can this tool run outside Docker, i.e. not as a container?

**Comment by dimtruck** [comment]
You can run the shell command directly on the host.  That's what we do.

(from README)

```
git clone https://github.com/docker/docker-bench-security.git
cd docker-bench-security
sh docker-bench-security.sh
```

**Comment by jianghaitao** [comment]
Thanks for pointing that out :) README is mostly about running it as a container, I was wondering usefulness of that, i.e. conflict between tool and goal. Running as CLI is actually very straightforward and much easier than trying to figure out why your docker-bench-security can not be run.

**Comment by katopz** [comment]
And if I want to run against Ubuntu14? `auditctl` is not there so I will need `distros/Dockerfile.debian` am I right? So I've to take DockerFIle approach also build image myself? 

Would be nice if `sh` also work with `auditctl` addition there (or maybe I'm doing it wrong?).

**Comment by konstruktoid** [comment]
Hi @katopz, yes that is correct. If you want the `auditctl` funtionality in a container you'll have to run a distro specific Dockerfile.

What do you mean with it would be nice if `sh` also worked with `auditctl`?

**Comment by katopz** [comment]
Hi @konstruktoid , I expected something like [docker-bench-security.sh](https://github.com/docker/docker-bench-security/blob/master/docker-bench-security.sh) for Ubuntu may be it should name like `docker-bench-security-debian.sh` so I can use it like...
```
git clone https://github.com/docker/docker-bench-security.git
cd docker-bench-security
sh docker-bench-security-debian.sh
```
Would be nice, Thanks

**Comment by konstruktoid** [comment]
The distro specific Dockerfiles is basically only useful if you're having host <-> container issues.
If you're using the standalone script and run it as you do in https://github.com/docker/docker-bench-security/issues/119#issuecomment-221184223, it should work regardless of the distribution.

**Comment by Illydth** [comment]
Given the OP's comments, I'm wondering about the viability of maintaining the containerized version of this tool myself.

For us, our method is to use Jenkins to pull the code from git (we heavily modify your base for our own docker installation methodology (different base directory, different socket file, etc.)), package it, push it to the docker server in question, run the command line tool, and then teardown with the results stored in Jenkins since it's all Standard output.

Works well, allows us to run it on a schedule on any docker server we'd like, and allows us to maintain a custom version at will.

Only problem will be with updates, but I'll cross that bridge when I get there.

**Comment by konstruktoid** [comment]
Inactive. Closing.
