### ISSUE TITLE
docker exec chek fails on containers without ps

### ISSUE THREAD

**Issue by tsDaenor** [docker/docker-bench-security#126]
some containers that do not have ps give warning "Docker exec fails" because executable file not found in $PATH, yet it is possible to exec into the container.

**Comment by konstruktoid** [comment]
Hi @tsDaenor and sorry for the late reply.
Yes, this is correct, the alternative would be parsing a list with known locations of, for example, sshd.

**Comment by konstruktoid** [comment]
Inactive. Closing.
