### ISSUE TITLE
Erroneous [WARN] 5.3  - Verify that containers are running only a single main process

### ISSUE THREAD

**Issue by jwilmoth** [docker/docker-bench-security#129]
Running the docker-bench-security.sh script produced a WARN entry for ensuring only one process is running inside the container.  Looking at the test for this check on https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf (docker exec $INSTANCE_ID ps -el) the output contains the ps process itself as well as the container's single process:

docker exec $INSTANCE_ID ps -el
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
4 S   600     1     0  0  80   0 - 706419 futex_ ?       00:03:22 java
4 R   600   128     0  0  80   0 -  2270 -      ?        00:00:00 ps

Adding the following would exclude the test from the search results and not produce a false negative.
docker exec $INSTANCE_ID ps -el **| grep -v ps**
docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64

**Comment by konstruktoid** [comment]
Hi @jwilmoth, the line for counting the number of processes is https://github.com/docker/docker-bench-security/blob/master/tests/5_container_runtime.sh#L65 and https://github.com/docker/docker-bench-security/blob/master/tests/5_container_runtime.sh#L78 is just to verify that `ps` is actually working.

Could you attach a log and example of it not working?

**Comment by jwilmoth** [comment]
Here's the relevant portion of the output from running docker-bench-security.sh after cloning the repo this morning.

[INFO] 5  - Container Runtime
[WARN] 5.1  - Verify AppArmor Profile, if applicable
[WARN]      * No AppArmorProfile Found: tiny_booth
[WARN] 5.2  - Verify SELinux security options, if applicable
[WARN]      * No SecurityOptions Found: tiny_booth
[WARN] 5.3  - Verify that containers are running only a single main process
[WARN]      * Too many processes running: tiny_booth
[PASS] 5.4  - Restrict Linux Kernel Capabilities within containers
[PASS] 5.5  - Do not use privileged containers
[PASS] 5.6  - Do not mount sensitive host system directories on containers
[PASS] 5.7  - Do not run ssh within containers
[PASS] 5.8  - Do not map privileged ports within containers
[PASS] 5.10 - Do not use host network mode on container
[WARN] 5.11 - Limit memory usage for container
[WARN]      * Container running without memory restrictions: tiny_booth
[WARN] 5.12 - Set container CPU priority appropriately
[WARN]      * Container running without CPU restrictions: tiny_booth
[WARN] 5.13 - Mount container's root filesystem as read only
[WARN]      * Container running with root FS mounted R/W: tiny_booth
[PASS] 5.14 - Bind incoming container traffic to a specific host interface
[PASS] 5.15 - Do not set the 'on-failure' container restart policy to always
[PASS] 5.16 - Do not share the host's process namespace
[PASS] 5.17 - Do not share the host's IPC namespace
[PASS] 5.18 - Do not directly expose host devices to containers
[INFO] 5.19 - Override default ulimit at runtime only if needed
[INFO]      * Container no default ulimit override: tiny_booth

The container runs a single process (a tomcat server jvm).  Below is output of running the ps command for the container flagged with multiple processes.

docker exec tiny_booth ps -el
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
4 S   600     1     0  0  80   0 - 706419 futex_ ?       00:03:53 java
4 R   600   208     0  0  80   0 -  2270 -      ?        00:00:00 ps

docker exec tiny_booth ps -el
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
4 S   600     1     0  0  80   0 - 706419 futex_ ?       00:03:53 java
4 R   600   213     0  0  80   0 -  2270 -      ?        00:00:00 ps

**Comment by konstruktoid** [comment]
@jwilmoth thanks for catching this, we tried to grep -v the arguments as well.
could you test https://github.com/docker/docker-bench-security/pull/130?

**Comment by jwilmoth** [comment]
I applied the same change locally and bingo!

**[PASS]** 5.3  - Verify that containers are running only a single main process

**Comment by konstruktoid** [comment]
Awesome! I'll merge.
Thanks for testing.
