### ISSUE TITLE
Can not wrong docker-bench-security on old docker daemon

### ISSUE THREAD

**Issue by chengweiv5** [docker/docker-bench-security#145]
As I see to communicate with docker daemon, docker client API version has to older than docker engine.

However, the README says it can be run since docker daemon 1.6.2, I think this isn't correct since docker-bench-security installed docker 1.10 which client API version is 1.22, which far more newer than docker daemon 1.6.2(1.18).

Since docker-bench-security installed docker 1.10 that means it only can be run on docker 1.10 and newer version, is it right?

**Comment by konstruktoid** [comment]
Hi @chengweiv5 and sorry for the late reply. 
You're absolutely correct and I've updated the documentation.
