### ISSUE TITLE
Mounting /etc to container /etc results in unexpected container failures

### ISSUE THREAD

**Issue by alexei-led** [docker/docker-bench-security#149]
I suggest to mount host `/etc` to `/host/etc` folder inside docker-bench-security container. Otherwise you overwrite container `/etc` folder.
This can cause different problems: for example in Alpine container you will see "xterm terminal not found" error, when running `clear` or `tput` command - as result of hiding default '/etc' folder.
This will require to update all checks that looks for files and directories under `/etc`. I suggest to check if `/host/etc` exists than use it as `/etc` folder.

**Comment by konstruktoid** [comment]
Do you mean that the docker-bench script fails in anyway, following the README instructions, when we're using `/etc:/etc`?

**Comment by konstruktoid** [comment]
Inactive. Closing.

**Comment by tatulea** [comment]
This still seems to be an issue. I'm using ubuntu:20.04 as a base docker image and the issue is that `/usr/bin/awk` is actually linked to `/etc/alternatives/awk`. My target system is CentOS and it does not have `/etc/alternatives/awk`
