### ISSUE TITLE
/var/lib/docker/devicemapper/mnt/d68c341169cec947dda3104e469511f132d31a757c5bc2ef947f349c0322ad08/rootfs/etc/hostname: read-only file system 

### ISSUE THREAD

**Issue by zopyx** [docker/docker-bench-security#15]
CentOS 6.6:

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

Timestamp: 2015-05-31 09:03:30.895404758 +0200 CEST
Code: System error

Message: open /var/lib/docker/devicemapper/mnt/d68c341169cec947dda3104e469511f132d31a757c5bc2ef947f349c0322ad08/rootfs/etc/hostname: read-only file system

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@29
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@29
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
FATA[0005] Error response from daemon: Cannot start container d68c341169cec947dda3104e469511f132d31a757c5bc2ef947f349c0322ad08: [8] System error: open /var/lib/docker/devicemapper/mnt/d68c341169cec947dda3104e469511f132d31a757c5bc2ef947f349c0322ad08/rootfs/etc/hostname: read-only file system

**Comment by zopyx** [comment]
Same issue on OpenSuSe 13.1

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
blackmoon2:/home/ajung # sh out 
Timestamp: 2015-06-01 15:37:31.928079769 +0200 CEST
Code: System error

Message: open /var/lib/docker/btrfs/subvolumes/5303b91b22d9b14fea93e7391163d605b0e59f068fc2a1d1973307557e9b1691/etc/hostname: read-only file system

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@29
---
1: Init
Package: FATA[0000] Error response from daemon: Cannot start container 5303b91b22d9b14fea93e7391163d605b0e59f068fc2a1d1973307557e9b1691: [8] System error: open /var/lib/docker/btrfs/subvolumes/5303b91b22d9b14fea93e7391163d605b0e59f068fc2a1d1973307557e9b1691/etc/hostname: read-only file system

**Comment by diogomonica** [comment]
@zopyx can you try to run the container without RO

```sh
docker run -it --net host --pid host -v /var/run/docker.sock:/var/run/docker.sock \
-v /usr/lib/systemd:/usr/lib/systemd -v /etc:/etc --label docker-bench-security \
diogomonica/docker-bench-security
```

**Comment by zopyx** [comment]
This is working

**Comment by diogomonica** [comment]
Great. I changed the readme to remove mounting as read-only. I was doing it to set a good example of how to run containers with increased isolation from your system, but this container is too privileged for this to matter.

Thank you for reporting this.
