### ISSUE TITLE
Replace auditctl with grep

### ISSUE THREAD

**Issue by alexei-led** [docker/docker-bench-security#150]
Some Linux distributions do not have `auditctl` installed. For example: Alpine Linux (your default Docker image). This results in multiple check failures.

I suggest to replace `auditctl` with `grep`. Or do it if `auditctl` is not installed, at least.
The following `grep` expression should work: search for audit on `$file`, skipping commented lines

```
grep "$file" "/etc/audit/audit.rules" | grep "^[^#;]" 
```

**Comment by konstruktoid** [comment]
Thank you for the suggestion @alexei-led, the issue is that we then get the configuration and not the what's currently audited, but I guess it's better that nothing at all.
I'll look into it.
