### ISSUE TITLE
Explanation of warnings

### ISSUE THREAD

**Issue by siddharthist** [docker/docker-bench-security#155]
When I run this script, I get several warnings that I don't quite understand, or that don't seem fully fleshed out. Many could just mention the docker daemon setting that they're talking about, like `--icc` for warning 1.10, or `--userns-remap` for 2.8. 

Here are some examples of more ambiguous warnings (sorry for the ANSI escape codes):
```
[WARN] 1.1  - Create a separate partition for containers
[WARN] 1.7  - Audit docker daemon - /usr/bin/docker
[WARN] 1.8  - Audit Docker files and directories - /var/lib/docker
[WARN] 1.9  - Audit Docker files and directories - /etc/docker
[WARN] 1.10 - Audit Docker files and directories - docker.service
[WARN] 4.1  - Create a user for the container
[WARN] 5.25 - Restrict container from acquiring additional privileges
[WARN] 5.20 - Do not share the host's UTS namespace
```
Sorry if these are clear to everyone else :bulb:

**Comment by konstruktoid** [comment]
Hi @siddharthist, so sorry for the late reply.
The tests are mapped against the CIS Docker 1.11.0 Benchmark, so for example test 1.10 is described on page 27 (1.10 Audit Docker files and directories - docker.service (Scored)). See https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.11.0_Benchmark_v1.0.0.pdf.

I hope that helps.

**Comment by siddharthist** [comment]
@konstruktoid Sure does :) might help to have a link to that page somewhere in the README!

**Comment by konstruktoid** [comment]
It's mentioned in the first section in the https://github.com/docker/docker-bench-security/blob/master/README.md.

**Comment by siddharthist** [comment]
:facepalm: thanks @konstruktoid!
