### ISSUE TITLE
daemon options can only be extracted from command line

### ISSUE THREAD

**Issue by dongalex** [docker/docker-bench-security#156]
Hi,

docker daemon holds an option --config-file and other options can be set inside the file. However, from your implementation, I can't see it supporting extracting options from the configuration file so it can only support extracting options set in command line.

Alex

**Comment by dongalex** [comment]
Any update?

**Comment by konstruktoid** [comment]
Hi @dongalex, please see https://github.com/docker/docker-bench-security/issues/157#issuecomment-233861181

**Comment by dongalex** [comment]
cool! thanks
