### ISSUE TITLE
Proposal: Use Docker Config Files to Override Settings

### ISSUE THREAD

**Issue by Illydth** [docker/docker-bench-security#157]
So one of the issues that's causing me to heavily modify the base code (which is easy enough since it's just a bunch of shell scripts) of this app is the fact that we've set our own standards for where to install and run Docker.

Initially, our docker filesystem runs out of /docker instead of /var/lib/docker and our socket file exists in the /docker area also.

All of these settings are stored in /etc/sysconfig (RHEL Based Distribution, I know it's different in Debian/Ubuntu).  It would be nice if the code took into consideration the various stored switches in the config files to override the defaults:  For instance, if the code looked for the "-g" option to the docker run line in /etc/sysconfig/docker and then overrode "directory" in 1.1 to point to the location specified by the -g command line switch.

Several things are gained by this methodology: you can override directories, check for networking options or even skip tests based upon understanding the default behavior of docker + what's configured in the config files.

**Comment by konstruktoid** [comment]
Hi @Illydth and thanks for you proposal. 
Using the configuration file is a viable solution, and I'm planning to go through all present issues when Docker 1.12 is released and the CIS-benchmark is updated.
