### ISSUE TITLE
Proposal: Update Check / Benchmark Numbers to Match CIS Document Sections

### ISSUE THREAD

**Issue by Illydth** [docker/docker-bench-security#159]
As it is right now, the checks in Docker-Bench in many cases do not match up to the current (1.6) version of the CIS document.  This means that when reading a WARN from the tool, we can't match it up to the CIS document to determine what that warning got produced from or what the recommendation is.

It would be EXCEPTIONALLY helpful if, upon updating, we could re-set the check numbers to identically match the CIS sections so that the tool is self referencing and self documenting.

**Comment by konstruktoid** [comment]
Hi @Illydth, the checks follows (or at least should) the latest release benchmark which currently is 1.11.0 https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.11.0_Benchmark_v1.0.0.pdf
