### ISSUE TITLE
Docker content trust test (4.5) will always fail when using pre-built container.

### ISSUE THREAD

**Issue by brettstover** [docker/docker-bench-security#164]
The README.md suggests using the pre-built container for running the tests as so:

docker run -it --net host --pid host --cap-add audit_control --rm \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /etc:/etc --label docker_bench_security \
    docker/docker-bench-security

When doing this, the test for docker content trust uses the environment variables of the container the docker-bench-security.sh script is run in and so will always report that the test has failed. 

This can be confirmed by overriding the entrypoint with /bin/sh, echo'ing DOCKER_CONTENT_TRUST to confirm it's not set, running the docker-bench-security.sh script, noting that the test fails, exporting DOCKER_CONTENT_TRUST=1 within the container, running the script again and noting that the test now passes.

I'm not sure the best way to resolve this. One way is to modify the above run command to copy over the DOCKER_CONTENT_TRUST environment variable like so:

docker run -it --net host --pid host --cap-add audit_control --rm \
    -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /etc:/etc --label docker_bench_security \
    docker/docker-bench-security

Any better ideas?

**Comment by konstruktoid** [comment]
Hi @brettstover and sorry about the very late reply. 
I believe that exporting the DOCKER_CONTENT_TRUST environment variable as you propose is an acceptable way to do it.
