### ISSUE TITLE
Tests 2.2 Set the logging level

### ISSUE THREAD

**Issue by kevinll** [docker/docker-bench-security#166]
From the Docker doc[1] there is more than `info` and `debug` log levels.
The current implementation[2] however doesn't seems to comply to the CIS benchmark[3] documentation, where CIS suggests to pass only if log-level is set to `info` OR non presence.

Current implementation for 2.2 is checking:
```shell
get_docker_effective_command_line_args '-l' | grep "debug" >/dev/null 2>&1
```

Is there a reason why the test is only checking if log level is set to `debug`, instead of CIS benchmark's advice?

[1] https://docs.docker.com/registry/configuration/#loglevel
[2] https://github.com/docker/docker-bench-security/blob/master/tests/2_docker_daemon_configuration.sh#L17
[3] https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.12.0_Benchmark_v1.0.0.pdf

**Comment by konstruktoid** [comment]
Hi @kevinll and thanks for opening this issue, docker-bench-security has not however implemented all tests according to the 1.12 benchmark. The current version is based on the CIS Docker 1.11 Benchmark.

**Comment by kevinll** [comment]
Thanks for replying @konstruktoid !
I did linked the 1.12 benchmark but looking back to CIS Docker 1.11, this specific test requirements did not change. It is asking to verify docker daemon is run with `--log-level="info"` flag. Is there a reason for the current implementation?

**Comment by konstruktoid** [comment]
You're right @kevinll, https://github.com/docker/docker-bench-security/blob/master/tests/2_docker_daemon_configuration.sh#L17, is incorrect. 
Thanks for finding and reporting it, feel free to submit a PR or leave this issue open and it will be fixed with the next update.
