### ISSUE TITLE
update README to reflect currently support docker engine. 

### ISSUE THREAD

**Issue by nicolaka** [docker/docker-bench-security#174]
README is outdated pointing out that 1.11 is the latest currently supported engine.

**Comment by konstruktoid** [comment]
Hi @nicolaka, which part of the README?
The only reference to 1.11 I see is "The tests are all automated, and are inspired by the CIS Docker 1.11  Benchmark." and this is still correct.

**Comment by nicolaka** [comment]
@konstruktoid I see that CIS still doesn't support 1.12. So officially last engine supported is 1.11 ?

**Comment by konstruktoid** [comment]
Not really, `docker-bench-security` is based on the CIS Benchmark for Docker 1.11 but can still be applied to Docker 1.12. There is a updated CIS document at https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.12.0_Benchmark_v1.0.0.pdf for 1.12, but this project hasn't been adapted to that version. 
Planning on going through the next CIS release and update `docker-bench-security`.

**Comment by kinghuang** [comment]
Is there any progress on updating `docker-bench-security` for the CIS Docker 1.12.0 Benchmark document? I find the combination of that document and the scripts in this repo really helpful. It'd be nice to get an update.

**Comment by konstruktoid** [comment]
Hi @kinghuang, the script and documentation will be updated when 1.13 has been released.

**Comment by konstruktoid** [comment]
Updating to 1.12/1.13 has begun. Closing.
