### ISSUE TITLE
Debian specific Dockerfile is not working on Jessie

### ISSUE THREAD

**Issue by fbiaustria** [docker/docker-bench-security#177]
Last working commit, which works for me is the following:
https://raw.githubusercontent.com/docker/docker-bench-security/930f7ea676bc52a205ea41c72721d5e6a3d4b3ec/distros/Dockerfile.debian

I tried running the build process on Jessie, also with Jessie base image and jessie dependencies, but it won't work as far as I can see.

**Comment by konstruktoid** [comment]
Hi @fbiaustria and thank you for reporting this. Could you please attach the build error and logs?

**Comment by fbiaustria** [comment]
This is the stout of the build process, hopefully you can extract the information you need. 

I guess the problem is that there is no binary of docker.io for debian stretch available:
"E: Package 'docker.io' has no installation candidate"

[docker-bench-security-build.txt](https://github.com/docker/docker-bench-security/files/625056/docker-bench-security-build.txt)

**Comment by konstruktoid** [comment]
Seems Docker, both docker.io and docker-engine, has been removed from majority of Debian releases.

https://packages.debian.org/search?suite=default&section=all&arch=any&lang=en&searchon=names&keywords=docker
https://packages.debian.org/search?suite=default&section=all&arch=any&lang=en&searchon=names&keywords=docker.io

Will need to use `sid`.
