### ISSUE TITLE
Why using alpine:3.2? 

### ISSUE THREAD

**Issue by pascalandy** [docker/docker-bench-security#183]
Hi,

I love this project and I will soon checkout the output recommendations.

**Question**: Why are we not using [alpine:3.5](https://hub.docker.com/_/alpine/) ? IMHO we shall use the latest stable OS.

Cheers!
https://twitter.com/_pascalandy

**Comment by konstruktoid** [comment]
Hi @pascalandy, and thanks for the reminder. 
As `alpine:3.2` has an End of Support 2017-05-01 and is receiving security updates this hasn't been a priority, but since that date is closing in and it's one less thing to remember, I'll submit a PR.
