### ISSUE TITLE
Sections 1.8 through 1.18 are failing on RHEL7 hosts

### ISSUE THREAD

**Issue by fatherlinux** [docker/docker-bench-security#19]
When I use the following command, these sections fail:

docker run -it --net host --pid host -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd -v /etc:/etc --label docker-bench-security diogomonica/docker-bench-security

Sections

[WARN] 1.8  - Failed to inspect: auditctl command not found.
[WARN] 1.9  - Failed to inspect: auditctl command not found.
[WARN] 1.10 - Failed to inspect: auditctl command not found.
[WARN] 1.11 - Failed to inspect: auditctl command not found.
[WARN] 1.12 - Failed to inspect: auditctl command not found.
[WARN] 1.13 - Failed to inspect: auditctl command not found.
[WARN] 1.14 - Failed to inspect: auditctl command not found.
[WARN] 1.15 - Failed to inspect: auditctl command not found.
[WARN] 1.16 - Failed to inspect: auditctl command not found.
[WARN] 1.17 - Failed to inspect: auditctl command not found.
[WARN] 1.18 - Failed to inspect: auditctl command not found.

However, if I run the script locally, it works

git clone https://github.com/diogomonica/docker-bench-security.git
cd docker-bench-security/
 bash docker-bench-security.sh

Sections
[PASS] 1.8  - Audit docker daemon
[PASS] 1.9  - Audit Docker files and directories - /var/lib/docker
[PASS] 1.10 - Audit Docker files and directories - /etc/docker
[PASS] 1.11 - Audit Docker files and directories - docker-registry.service
[PASS] 1.12 - Audit Docker files and directories - docker.service
[PASS] 1.13 - Audit Docker files and directories - /var/run/docker.sock
[PASS] 1.14 - Audit Docker files and directories - /etc/sysconfig/docker
[PASS] 1.15 - Audit Docker files and directories - /etc/sysconfig/docker-network
[PASS] 1.16 - Audit Docker files and directories - /etc/sysconfig/docker-registry
[PASS] 1.17 - Audit Docker files and directories - /etc/sysconfig/docker-storage
[PASS] 1.18 - Audit Docker files and directories - /etc/default/docker

I had a suspicion that it might be something in the container, so I built my own version from RHEL:

Dockerfile
FROM rhel7

RUN yum install -y yum-utils; yum clean all
RUN yum-config-manager --disable "*" &>/dev/null
RUN yum-config-manager --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms
RUN yum install -y docker net-tools; yum clean all
RUN mkdir /docker-bench-security
COPY . /docker-bench-security
WORKDIR /docker-bench-security
ENTRYPOINT ["/bin/sh", "docker-bench-security.sh"]

Build
docker build -t fatherlinux/docker-bench-security .

While it builds and runs properly, I get the same failures:

[WARN] 1.8  - Failed to inspect: auditctl command not found.
[WARN] 1.9  - Failed to inspect: auditctl command not found.
[WARN] 1.10 - Failed to inspect: auditctl command not found.
[WARN] 1.11 - Failed to inspect: auditctl command not found.
[WARN] 1.12 - Failed to inspect: auditctl command not found.
[WARN] 1.13 - Failed to inspect: auditctl command not found.
[WARN] 1.14 - Failed to inspect: auditctl command not found.
[WARN] 1.15 - Failed to inspect: auditctl command not found.
[WARN] 1.16 - Failed to inspect: auditctl command not found.
[WARN] 1.17 - Failed to inspect: auditctl command not found.
[WARN] 1.18 - Failed to inspect: auditctl command not found.

Any ideas on what could be happening or how to troubleshoot?

**Comment by diogomonica** [comment]
@fatherlinux the issue is that inside of the container `auditctl` doesn't exist. When you run directly from the command line using `sh script.sh`, it uses the hosts binaries to check for the benchmark. When you run the container, it uses the container's binaries.

We're using Alpine Linux for the base layer, and unfortunately I don't see any packages to bring auditctl in. I might have to change the base layer to use a distro that has it.

**Comment by fatherlinux** [comment]
@iogomonica, you were right. I installed auditctl and a few other packages to make things work with a rhel container. I have generated a pull request. I am working on a centos specific Dockerfile too, I will generate a pull request when I am finished.

Also, you have to run the "docker run" command with the --privileged flag or things will not work right because of a bug in auditd where it can not be ran with dropped privs:

https://bugzilla.redhat.com/show_bug.cgi?id=709345

**Comment by fatherlinux** [comment]
Dockerfile for CentOS working and tested... woo hoo

**Comment by konstruktoid** [comment]
This isn't isolated to RH since the package is missing inside the container. 
What are we aiming for with a RHEL and Centos dockerfile? If we get the container functionality we want , isn't size the deciding factor?

**Comment by fatherlinux** [comment]
So, I think there is a common misconception that what operating system is inside the container doesn't matter. That said, there are entry of security minded people that very much believe it does [1].

I think there are also a number of people that are skeptical from a functionality perspective [2].

My goal is to allow security minded people to build a CIS Benchmark container with a userspace that matches their underlying OS [3]. Or, at a minimum, some thing very close, like Centos to RHEL. I hope that makes sense, especially from a security perspective. Knowing where the container users pace comes from is quite important!

[1]: http://crunchtools.com/securing-docker-svirt/
[2]: http://www.fewbytes.com/docker-selinux-and-the-myth-of-kernel-indipendence/
[3]: http://crunchtools.com/meeting-cis-benchmark/

**Comment by konstruktoid** [comment]
I totally agree with you, except perhaps the part about "underlying OS" since it assumes that the underlying OS is RHEL/CentOS in this case.

**Comment by fatherlinux** [comment]
Yeah, my apologies, I should have clarified. My goal is to have a CIS Benchmark container as an option for RHEL and CentOS users (underlying OS). The second goal is to allow them to build it themselves (for trust reasons).

I am not trying to prescribe that RHEL/CentOS is the best. If a user were using Ubuntu for the underlying OS, I would recommend a custom built Ubuntu userspace (container) for the same reason.

**Comment by konstruktoid** [comment]
Since the issue is that the auditctl command isn't present in Alpine distro and (in response to https://github.com/docker/docker-bench-security/issues/19#issuecomment-108170797) cap_audit_control is needed (https://github.com/docker/docker-bench-security/commit/cf7b13d5ba0f550424cf25eca0189c99a8fa3684), can this issue be closed and then create a new base image proposal (the Debian failed, https://github.com/docker/docker-bench-security/pull/28#issuecomment-112187325) ?

**Comment by fatherlinux** [comment]
I think closing this is fine. Is there a way you could add my Dockerfile.centos and Dockerfile.redhat files as an option for users? Perhaps you could create a distros directory?

I really don't think you are going to find an "official" image distro (like Alpine) that will work for everyone (underlying OS) CentOS/Red Hat, CoreOS, Debian/Ubuntu, etc.

I suspect it's best to just let people build whatever they want....

**Comment by konstruktoid** [comment]
That sounds like a good idea @fatherlinux in my opinion.
`distros/Dockerfile.{distribution}` 

@diogomonica?

**Comment by snrism** [comment]
@fatherlinux @diogomonica : Any plans to add distro directory or move to a different base image? This can allow users to work with their OS and can save some cycles by avoiding the "command not found" error. 

In my version, I skip 1.9-1.18,  if 1.8 fails with "Failed to inspect: auditctl command not found." error. Something like below. 

# 1.8
check_1_8="1.8  - Audit docker daemon"
command -v auditctl >/dev/null 2>&1
...
else
  warn "1.8  - Failed to inspect: auditctl command not found."
  warn "     * Skipping remaining auditctl tests"
  continue
fi

This way, the execution continues with the next file. However, this will only be a temp fix, cos if you add tests that are not based on auditclt after 1.18, `continue` will skip that too.

**Comment by diogomonica** [comment]
@snrism just merged @konstruktoid's PR. We now have a distro directory with a contribution README.

**Comment by konstruktoid** [comment]
Close thanks to #50?

**Comment by snrism** [comment]
@diogomonica Thanks!

**Comment by konstruktoid** [comment]
Closing because #50 was merged.
