### ISSUE TITLE
CPU information misleading

### ISSUE THREAD

**Issue by amouat** [docker/docker-bench-security#21]
The benchmark reports:

    [WARN]      * Container running without CPU restrictions: 9f39cbf8e538

This is misleading at best, as CPU shares are relative and set by default. This means that a user who doesn't set any CPU shares will find that all containers share CPU equally when under load. Contrast this with a user who sets containers to a share of 10 by default, if they accidentally set a container to 100 or forget to set a value for a container, they will be in *much* worse position with one container getting the lion's share of resources.

**Comment by diogomonica** [comment]
Adrian, thank you for submitting the issue.

This tool checks for the automatable tests of the Docker CIS Benchmark: https://benchmarks.cisecurity.org/downloads/show-single/?file=docker16.100

The Benchmark itself is an open initiative together with the Center for Internet Security. While I understand your comment, this is better addressed in the discussion around the benchmark document itself.

**Comment by amouat** [comment]
OK. I have read the document. Is there an open discussion somewhere? 

As it stands, I think this rule is actively harmful as it is encouraging users to change something they may not understand.

**Comment by diogomonica** [comment]
Adrian, I think you can do it here: https://benchmarks.cisecurity.org/community/projects/

**Comment by amouat** [comment]
Thanks!

**Comment by diogomonica** [comment]
Thank you Adrian. Would love to have you participate on the next version of the Benchmark.
