### ISSUE TITLE
Test 5.5 say my container have mounted /lib /etc ... from host but this is not true

### ISSUE THREAD

**Issue by immae1** [docker/docker-bench-security#212]
if i inspect my running web container i got this:
```
"Volumes": {
                "/db": {},
                "/etc/ssh": {},
                "/home/user/.pycharm_helpers": {},
                "/home/user/files": {},
                "/home/user/app": {}
            },
```
but if i run the benchtests i get the information that my containers have mounted sensitive dirs from host:
```
[WARN] 5.5  - Do not mount sensitive host system directories on containers
[WARN]      * Sensitive directory /etc mounted in: web_1
[WARN]      * Sensitive directory /lib mounted in: web_1
[WARN]      * Sensitive directory /proc mounted in: web_1
```
If i use the recommended audit command from CIS i got this error:
`Template parsing error: template: :1: unclosed action 
`
if i run this "docker inspect --format '{{ .VolumesRW }}' "web_1" 2>/dev/null 1>&2;" command from the tests i get the error: 
Template parsing error: template: :1:3: executing "" at <.VolumesRW>: map has no entry for key "VolumesRW" 

I don't unterstand why the tests says that /lib and /proc are mounted. i run the tests on a ubuntu:trusty system. 
Maybe i make something wrong?! 
Thanks

**Comment by konstruktoid** [comment]
Hi again @immae1, 
The `.VolumesRW` error is depending on the version you're using. I don't get `/proc` but `/lib` is a false positivt due to  `/var/lib/docker/volumes/`.

Could you paste your `docker inspect --format '{{ .VolumesRW }}' web_1` output?

```
$ docker inspect --format '{{ .VolumesRW }}' test_FAIL_5_5
Template parsing error: template: :1:3: executing "" at <.VolumesRW>: map has no entry for key "VolumesRW"
$ docker inspect --format '{{ .Mounts }}' test_FAIL_5_5
[{bind  /tmp /tmp/htmp   true } {bind  /etc /tmp/etc   true } {volume 7ab5747b595e1e0ea0690d6fb0edb2493c3096ea4dfefd0bc769702e8b263515 /var/lib/docker/volumes/7ab5747b595e1e0ea0690d6fb0edb2493c3096ea4dfefd0bc769702e8b263515/_data /etc/ssh local  true }]
```

**Comment by immae1** [comment]
HI @konstruktoid,
sorry for the late response.
```
root@vagrant-ubuntu-trusty-64:~/docker-bench-security# docker inspect --format '{{ .VolumesRW }}' web_1

Template parsing error: template: :1:3: executing "" at <.VolumesRW>: map has no entry for key "VolumesRW"
```

**Comment by konstruktoid** [comment]
The `/lib` false positive is due to the fact `/var/lib/` is in there, but does the script warn about `/proc` when you're running `docker inspect --format '{{ .Mounts }}' app_web_1`?

**Comment by immae1** [comment]
The the skript does warn about:
[WARN]      * Sensitive directory /etc mounted in: app_web_1
[WARN]      * Sensitive directory /lib mounted in: app_web_1
[WARN]      * Sensitive directory /proc mounted in: app_web_1

if i run your command i got:
```
root@vagrant-ubuntu-trusty-64:/tmp/docker-bench-security# docker inspect --format '{{ .Mounts }}' app_web_1
[
{volume app_files /var/lib/docker/231072.231072/volumes/app_files/_data /home/user/files local rw true }
{volume app_db /var/lib/docker/231072.231072/volumes/app_db/_data /db local rw true }
{volume app_ssh-config /var/lib/docker/231072.231072/volumes/app_ssh-config/_data /etc/ssh local rw true }
{volume app_helpers /var/lib/docker/231072.231072/volumes/app_helpers/_data /home/user/.pycharm_helpers local rw true }
 {bind  /home/vagrant/appdir /home/user/app  rw true }
 ]

```

i think /proc and /etc is wrong - i don't see that are mountes in container.
I run this this project in a vagrant vm - maybe this is the problem? 
Greetings

**Comment by konstruktoid** [comment]
Sorry for the late reply @immae1, and yes the test should only check the first part of the path.

**Comment by konstruktoid** [comment]
@immae1 could you try with https://github.com/docker/docker-bench-security/pull/216?

**Comment by immae1** [comment]
@konstruktoid 
after i fetched your pull request i run the test:
[PASS] 5.5  - Do not mount sensitive host system directories on containers 

but if i test to mount a sensitive volume with this:
$ docker run -d -P -v /:/etc/test ubuntu:trusty tail -f /dev/null
the test output is  [PASS] 5.5  - Do not mount sensitive host system directories on containers

i think there is bug in your pull request or i make a mistake to test it? 
Greetings

**Comment by konstruktoid** [comment]
#216 updated
