### ISSUE TITLE
Daemon configuration tests do not consider options in daemon.json

### ISSUE THREAD

**Issue by kinghuang** [docker/docker-bench-security#213]
There are several tests, especially in the 2.x and 3.x sections, that are based on parsing the `docker daemon` or `dockerd` command line arguments via `get_docker_cumulative_command_line_args` and checking for certain options. However, this ignores the fact that [Docker daemon configurations can also be set in a file](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file), typically at `/etc/docker/daemon.json`. Because of this, the tests can give erroneous output.

For example, the output for test 2.6 tells me that the Docker daemon is not listening on TCP. In reality, my daemon is listening on `tcp://0.0.0.0:2376` and has TLS authentication configured.

docker-bench-security output for 2.6:

```
[INFO] 2.6  - Configure TLS authentication for Docker daemon
[INFO]      * Docker daemon not listening on TCP
```

Excerpt from daemon.json:

```
	"hosts": [
		"unix:///var/run/docker.sock",
		"tcp://0.0.0.0:2376"
	],
	"tlsverify": true,
	"tlscacert": "/etc/docker/certs.d/ca.pem",
	"tlscert": "/etc/docker/certs.d/server-cert.pem",
	"tlskey": "/etc/docker/certs.d/server-key.pem"
```

**Comment by konstruktoid** [comment]
Hi @kinghuang, and thank you for bringing this up. Support for handling a configuration file will be looked into now that 1.13 has been release, it's been on the back burner for a while now.

Also see issue #157

**Comment by willfarrell** [comment]
Using `jq` would make this easy to do. 

2.2 example: `cat /etc/docker/daemon.json | jq -r '.["log-level"]'`

**Comment by konstruktoid** [comment]
Please test #218. @Illydth @kinghuang

**Comment by kinghuang** [comment]
@konstruktoid Just gave #218 a try! I repeatedly got `grep: : No such file or directory` in the output, and it did not pick up my settings in `daemon.json`. I don't think `get_docker_configuration_file_args()` is handling the case where `--config-file` isn't explicitly set, and the default value `/etc/docker/daemon.json` is being used.

**Comment by konstruktoid** [comment]
Thanks for catching this, updated.

**Comment by konstruktoid** [comment]
Stil an issue when there's not CLI options are used and no config file present.
