### ISSUE TITLE
docker-bench-security.sh shows v1.3.0 for v1.3.1 tag

### ISSUE THREAD

**Issue by kinghuang** [docker/docker-bench-security#230]
**Description**

The `docker-bench-security.sh` script for the `v1.3.1` tag displays *Docker Bench for Security v1.3.0* in the output.

**Steps to reproduce the issue:**

1. Download the code for the [`v1.3.1` release](https://github.com/docker/docker-bench-security/releases/tag/v1.3.1). 
2. Run `docker-bench-security.sh`.

**Describe the results you received:**

The second line of output is: `# Docker Bench for Security v1.3.0`

**Describe the results you expected:**

The second line of output should be: `# Docker Bench for Security v1.3.1`

**Comment by konstruktoid** [comment]
Correct @kinghuang, a miss from my part.  I will update as soon as possible.

**Comment by konstruktoid** [comment]
Updated the version to 1.3.2 before release.
