### ISSUE TITLE
Test 2.6 does not detect whether Docker daemon is listening on TCP when using daemon.json

### ISSUE THREAD

**Issue by kinghuang** [docker/docker-bench-security#231]
**Description**

Test 2.6—Configure TLS authentication for Docker daemon—has an incorrect check for whether the Docker daemon is listening on TCP.. The configuration file args implementation first checks for `tls`, then `tlskey`, and finally `tlsverify`. The command line args implementation checks for `-H`, then `--tlskey`, and finally `--tlsverify`.

This leads to the configuration file path to incorrectly determine that a Docker daemon is not listening on TCP if it uses an implicit `tls` option. The [dockerd documentation](https://docs.docker.com/engine/reference/commandline/dockerd/) for `--tls` says, “use TLS; implied by `–tlsverify`.”

The configuration file args path should do the same check as the command line args path (i.e., check if `hosts` is defined for something other than `(unix|fd)://`), or handle an implicit `tls` option from `tlsverify`.

**Steps to reproduce the issue:**

1. Configure a Docker Engine using a `daemon.json` with `tlsverify` set to `true`. 
2. Run `docker-bench-security.sh`.

**Describe the results you received:**

Test 2.6 says the Docker daemon is not listening on TCP.

```
[INFO] 2.6  - Configure TLS authentication for Docker daemon
[INFO]      * Docker daemon not listening on TCP
```

**Describe the results you expected:**

Test 2.6 should pass.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is based on the `v1.3.1` release.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Here's my `daemon.json`. I have `hosts` defined and listening on TCP, and `tlsverify` set to true.

```
{
	"disable-legacy-registry": true,
	"experimental": true,
	"storage-driver": "devicemapper",
	"storage-opts" : [
		"dm.thinpooldev=/dev/mapper/docker-thinpool",
		"dm.use_deferred_removal=true"
	],
	"hosts": [
		"unix:///var/run/docker.sock",
		"tcp://0.0.0.0:2376"
	],
	"metrics-addr": "0.0.0.0:9323",
	"tlsverify": true,
	"tlscacert": "/etc/docker/certs.d/ca.pem",
	"tlscert": "/etc/docker/certs.d/server-cert.pem",
	"tlskey": "/etc/docker/certs.d/server-key.pem"
}
```

**Comment by konstruktoid** [comment]
Hi @kinghuang, sorry for the late reply and thanks for reporting this. I will look into it and update as soon as possible.

**Comment by konstruktoid** [comment]
Please test https://github.com/docker/docker-bench-security/pull/234

**Comment by kinghuang** [comment]
@konstruktoid On #234, it's correctly reporting that the daemon is listening on TCP, but it's not detecting the use of TLS.

```
[WARN] 2.6  - Configure TLS authentication for Docker daemon
[WARN]      * Docker daemon currently listening on TCP without TLS
```

I have `tlsverify` set to true in my `daemon.json`, but I do not have `tls` defined. The [dockerd documentation](https://docs.docker.com/engine/reference/commandline/dockerd/) for `tls` says that it can be implied by `tlsverify`.

**Comment by konstruktoid** [comment]
Thanks for the comment, will fix.

**Comment by konstruktoid** [comment]
https://github.com/docker/docker-bench-security/pull/234/commits/754e0ed02bc9b7175890e7d5a7f25b6bc162314d

**Comment by kinghuang** [comment]
754e0ed looks good!

```
[PASS] 2.6  - Configure TLS authentication for Docker daemon
```

I also tried with `"tls": true` and `"tlsverify": false` to make sure it works for those conditions.
