### ISSUE TITLE
Network hardening checks

### ISSUE THREAD

**Issue by rhonnava** [docker/docker-bench-security#239]
It would help if docker bench security checks for network stack hardening parameters for some basic attacks like SYN flooding, for parameters available per container: 
 - If syn cookie protection is enabled in /proc/sys/net/ipv4/tcp_syncookies 
 - Reducing the time for half opened connections in the backlog queue by limiting tcp_synack_retries 
 - Increasing the backlog queue

Protection against IP Spoofing:
 - Turn on source address validation: net.ipv4.conf.all.rp_filter

Enable logging of redirect packets, spoofed packets, source routed packets:
net.ipv4.conf.all.log_martians = 1 

And any other such network parameter ....

**Comment by konstruktoid** [comment]
Hi @rhonnava, I understand why you'd want this, but `docker-bench-security` is focused on following the CIS Docker Benchmark and not really server hardening in general.
I suggest you have a look at other CIS benchmarks (https://learn.cisecurity.org/benchmarks), DISA STIGs (http://iase.disa.mil/stigs/Pages/index.aspx) or OpenSCAP (https://github.com/OpenSCAP/scap-security-guide/).
