### ISSUE TITLE
Consider including Inspec resources?

### ISSUE THREAD

**Issue by anweiss** [docker/docker-bench-security#240]
In addition to the current scripting mechanism by which Docker bench operates, it would be cool to consider the inclusion of InSpec (http://inspec.io/) resources that can also be used to validate Engine configurations per the CIS Benchmark.

**Comment by konstruktoid** [comment]
Hi @anweiss, I'll have a look at InSpec. Thanks for bringing this to my attention.

**Comment by anweiss** [comment]
As an FYI, we're also looking to incorporate the use of Inspec in our compliance guidance repo here -> https://github.com/docker/ddc-opencontrol/issues/20 ... so some solid overlap potential

**Comment by konstruktoid** [comment]
The thing is that Docker bench then goes from a basic, portable POSIX, script to a tool that requires a new set of tools, knowledge about InSpec and might exclude a number of users.
Also see https://github.com/docker/docker-bench-security/pull/147

**Comment by anweiss** [comment]
Agreed. So rather than replace the existing POSIX, Inspec could be a complement.

**Comment by konstruktoid** [comment]
Separate project perhaps, a clean InSpec implementation of the CIS benchmark?
But as seen in #147 this might conflict with https://github.com/diogomonica/actuary @diogomonica

**Comment by anweiss** [comment]
Working on this here -> https://github.com/docker/compliance/tree/inspec/inspec/cis-docker-benchmark

**Comment by anweiss** [comment]
Going to reference https://github.com/dev-sec/cis-docker-benchmark.
