### ISSUE TITLE
Parseable friendly ouput

### ISSUE THREAD

**Issue by dgonzalez** [docker/docker-bench-security#247]
Hi, I am wondering if it would be possible to produce a parser friendly output (like JSON) in order to automate the scanning of vulnerabilities with a bit of easiness instead of many regular expressions.

**Comment by konstruktoid** [comment]
Hi @dgonzalez, and thanks for the input. I'll have a look at it, but can't promise a timeline.

**Comment by dgonzalez** [comment]
I am totally swamped now but I can try to have a look since next week on.

**Comment by lizrice** [comment]
We have a [similar tool for the Kubernetes benchmark](github.com/aquasecurity/kube-bench) which can output in JSON as well as human-readable format. The tests are defined in YAML files, and I don't think it would take much to have it run Docker benchmark tests instead. Does that sound interesting @dgonzalez @konstruktoid?

**Comment by konstruktoid** [comment]
Sorry for the very, very late comment. Any progress on this?

**Comment by lizrice** [comment]
@konstruktoid will you be at DockerCon in Copenhagen? We could sync up about this there, if that suits.

**Comment by konstruktoid** [comment]
I won't be able to make it to Copenhagen this year sorry to say @lizrice

**Comment by dgonzalez** [comment]
What about an online meeting? we can have a call and articulate this. It is quite awkward to parse the output and it is not really human friendly as it is right now...

**Comment by konstruktoid** [comment]
I've made some kind of example, it logs to `$logger.json`:
```{
 "start": 1507636447,
  "1.1": "WARN",
  "1.2": "INFO",
  "1.3": "PASS",
  "1.4": "docker:x:993:vagrant",
  "1.5": "WARN",
  "end": 1507636448
}```

Document format is up for discussion of course, see #264

**Comment by konstruktoid** [comment]
Not meant to close.

**Comment by konstruktoid** [comment]
I'll add all check results later this week.

**Comment by konstruktoid** [comment]
I believe all tests have been added, so please test #264

**Comment by konstruktoid** [comment]
Merged.
