### ISSUE TITLE
1.11/1.12 Audit Docker files and directories - assumes docker is run under systemd

### ISSUE THREAD

**Issue by ajohnstone** [docker/docker-bench-security#25]
1.11 Audit Docker files and directories - docker-registry.service

```bash
# 1.11
check_1_11="1.11 - Audit Docker files and directories - docker-registry.service"
command -v auditctl >/dev/null 2>&1
if [ $? -eq 0 ]; then
  auditctl -l | grep /usr/lib/systemd/system/docker-registry.service >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    pass "$check_1_11"
  else
    warn "$check_1_11"
  fi
else
  warn "1.11 - Failed to inspect: auditctl command not found."
fi
```

1.12 Audit Docker files and directories - docker.service (Scored)

```
# 1.12
check_1_12="1.12 - Audit Docker files and directories - docker.service"
command -v auditctl >/dev/null 2>&1
if [ $? -eq 0 ]; then
  auditctl -l | grep /usr/lib/systemd/system/docker.service >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    pass "$check_1_12"
  else
    warn "$check_1_12"
  fi
else
  warn "1.12 - Failed to inspect: auditctl command not found."
fi
```

**Comment by konstruktoid** [comment]
This is the correct behavior since 1.11 and 1.12 in CIS Docker 1.6 Benchmark
v1.0.0 - 04-22-2015 p. 23-24 states that you should 
"Audit /usr/lib/systemd/system/docker-registry.service, if applicable." 
"Audit /usr/lib/systemd/system/docker.service, if applicable."

**Comment by ajohnstone** [comment]
Thanks for the quick reply @konstruktoid

if it's not applicable (I.e systemd is not the process to spawn docker or the registry) then should warn mark potential issues as red?

Something marked as red on a report indicates to me that it needs to be addressed rather than a warm/notice?

**Comment by konstruktoid** [comment]
I believe #26 resolves this issue.
