### ISSUE TITLE
Does docker bench security support Amazon Linux?

### ISSUE THREAD

**Issue by teo-scout24** [docker/docker-bench-security#253]
Hi, is it feasible to use this tool for Amazon Linux?

There are some differences between Amazon vs CentOS/RHEL, is this going to be a problem?

Thanks.

**Comment by konstruktoid** [comment]
Hi @teo-scout24, yes it should be feasible to use this on any Linux distribution as long as there's a standard Docker installation (`/var/run/docker.sock`, or `daemon.json`).
But please report any issues.

**Comment by teo-scout24** [comment]
Thanks
