### ISSUE TITLE
[WARN] 4.1  - Ensure a user for the container has been created

### ISSUE THREAD

**Issue by nicorevin** [docker/docker-bench-security#254]
I am not sure if it is the right place to report the issue but the "[Ensure non-root user is running](https://github.com/docker/docker-bench-security/blob/5d8f34954f81717b571cb88661edb8bfa6a43ca9/tests/4_container_images.sh)" is a bit misleading.

There is a bunch of software that is executed as a root but it changes the context like:
```
dhcpd -4 -f -d --no-pid -cf /etc/dhcp/dhcpd.conf -user dhcp -group dhcp
```
There is no need to create a separate USER for dhcp inside a Dockerfile and it seems to be pretty legit.

If this is me who understands this security case wrong please let me know. I will highly appreciate.

**Comment by konstruktoid** [comment]
You're correct @nicorevin, the test checks if `USER` is used and not if any forked non-privileged child processes is present.

The issue is how we should check if a non-privileged process is present in a specific container.
And to be a bit more bureaucratic, `4.1 Ensure a user for the container has been created` uses `docker ps --quiet --all | xargs docker inspect --format '{{ .Config.User }}'` as audit example.

```$ docker run --name konstruktoid_nginx -d -p 443:443 konstruktoid/nginx
caa5233f831b947d0895340eeb599410b33f550e1ddd111409566013c7355644
$ docker inspect --format 'User={{.Config.User}}' konstruktoid_nginx
User=
$ docker exec -ti konstruktoid_nginx ps -fe
PID   USER     TIME   COMMAND
    1 root       0:00 nginx: master process /usr/sbin/nginx -g daemon off;
    7 nginx      0:00 nginx: worker process
    8 nginx      0:00 nginx: worker process
    9 nginx      0:00 nginx: worker process
   10 nginx      0:00 nginx: worker process
   11 root       0:00 ps -fe
```

```$ docker run -ti konstruktoid/debian:7 /bin/ps -fe
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/bin/ps\": stat /bin/ps: no such file or directory".
$ docker run -ti konstruktoid/debian:7 /bin/sh
# ps -fe
/bin/sh: 1: ps: not found
# 
```
