### ISSUE TITLE
Disable Checks in scripts

### ISSUE THREAD

**Issue by karthik101** [docker/docker-bench-security#267]
I'm actually like to disable/skip few checks, I can remove the checks manually from the scripts. Can you implement any option that i can pass the check number to the main docker_benchmarking.sh script? 

A role based option that would allow certain checks to skip or enforce will be good.

Example:    ./docker_benchmarking.sh 5.11 4.10 ......

**Comment by konstruktoid** [comment]
Hi @karthik101, yeah that has been in the planning stage, and forgotten about now and then, since #51. 
I'll start working on it, but it will require some amount of rewriting.

**Comment by karthik101** [comment]
Thanks for the reply, will be looking froward to it, I'm working on the script to fix host, daemon WARN checks that will execute right after this.

**Comment by CameronLonsdale** [comment]
This feature would be great :)

**Comment by konstruktoid** [comment]
Script updated with the `-c` option where you can specify a specific check or group of checks, see `functions_lib.sh`

**Comment by konstruktoid** [comment]
I believe this was solved with #283. Closing.
