### ISSUE TITLE
Bug - 5.21 Incorrect grep pattern

### ISSUE THREAD

**Issue by CameronLonsdale** [docker/docker-bench-security#277]
I believe the grep pattern for check 5.21 is incorrect. Where it searches for `seccomp:unconfined`, it should be `seccomp=unconfined`.

With a container started with the `--security-opt seccomp=unconfined` option, In the latest version of docker, it appears that the command `$ docker inspect --format 'SecurityOpt={{.HostConfig.SecurityOpt }}' <container_id>` returns the option in the following format:

`SecurityOpt=[seccomp=unconfined]`

As a result, test 5.21 will report incorrect results.

Additional test information:

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by konstruktoid** [comment]
Hi @CameronLonsdale and nice catch, it seems it depends on how you add the `seccomp` option:
```
$ docker inspect --format 'SecurityOpt={{.HostConfig.SecurityOpt }}' 592 ec0 test_FAIL_5_21
SecurityOpt=[seccomp=unconfined]
SecurityOpt=[]
SecurityOpt=[seccomp:unconfined]
```
