### ISSUE TITLE
docker-security-scanning and relation to docker-bench-security

### ISSUE THREAD

**Issue by sundeepk1** [docker/docker-bench-security#294]
Hi,

Can you please tell me how is ths related to docker-security-scanning feature

**Comment by konstruktoid** [comment]
"Docker Security Scanning is available as an add-on to Docker hosted private repositories on both Docker Cloud and Docker Hub. The feature is available as a free preview for private repository subscribers for a limited time." https://docs.docker.com/docker-cloud/builds/image-scan/
`docker-bench-security` is a free CLI shell script for local usage.

**Comment by sundeepk1** [comment]
Thanks Thomas

Envoyé de mon iPhone

Le 28 mars 2018 à 13:21, Thomas Sjögren <notifications@github.com<mailto:notifications@github.com>> a écrit :


"Docker Security Scanning is available as an add-on to Docker hosted private repositories on both Docker Cloud and Docker Hub. The feature is available as a free preview for private repository subscribers for a limited time." https://docs.docker.com/docker-cloud/builds/image-scan/
docker-bench-security is a free CLI shell script for local usage.
