### ISSUE TITLE
Passing options into docker run

### ISSUE THREAD

**Issue by jammasterj89** [docker/docker-bench-security#296]
I was wondering if it was possible to pass any of the options (-h, -l, -c, -x) into docker-bench-security.sh directly from the docker run command? I've tried overwriting with the --entrypoint flag but can't get this to work, I was wondering if it was even possible?

Thank you!

**Comment by konstruktoid** [comment]
Thanks @jammasterj89 for taking the time reporting this, please update the repository and use the new Dockerfile.
Hope that helps.

**Comment by jammasterj89** [comment]
Thank you very much for the quick fix @konstruktoid! I've just tested it, and -l, -h and -c work fine, however I am not sure -x is working as it is not excluding any tests?

    docker run -it --net host --pid host --userns host --cap-add audit_control \
    -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /etc:/etc --label docker_bench_security \
    docker/docker-bench-security -c check_1_1 

    ...
    [WARN] 1.1  - Ensure a separate partition for containers has been created

    [INFO] Checks: 1
    [INFO] Score: -1
------
    docker run -it --net host --pid host --userns host --cap-add audit_control \
    -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /etc:/etc --label docker_bench_security \
    docker/docker-bench-security -x check_1_1

     ...
    [INFO] 1 - Host Configuration
    [WARN] 1.1  - Ensure a separate partition for containers has been created
    [NOTE] 1.2  - Ensure the container host has been Hardened
    [INFO] 1.3  - Ensure Docker is up to date
    ...

Thanks again,

**Comment by konstruktoid** [comment]
`-x` is a comma delimited list of patterns within a **container name to exclude from check**, it excludes containers not tests.

```
$ docker run -it --net host --pid host --cap-add audit_control     -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST     -v /var/lib:/var/lib     -v /var/run/docker.sock:/var/run/docker.sock     -v /usr/lib/systemd:/usr/lib/systemd     -v /etc:/etc --label docker_bench_security     docker-bench-security -c check_4_1
[...]
[WARN] 4.1  - Ensure a user for the container has been created
[WARN]      * Running as root: neutral
[WARN]      * Running as root: public
[WARN]      * Running as root: excluded

[INFO] Checks: 1
[INFO] Score: -1
$ docker run -it --net host --pid host --cap-add audit_control     -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST     -v /var/lib:/var/lib     -v /var/run/docker.sock:/var/run/docker.sock     -v /usr/lib/systemd:/usr/lib/systemd     -v /etc:/etc --label docker_bench_security     docker-bench-security -c check_4_1 -x excluded
[...]
[WARN] 4.1  - Ensure a user for the container has been created
[WARN]      * Running as root: neutral
[WARN]      * Running as root: public

[INFO] Checks: 1
[INFO] Score: -1
```

**Comment by jammasterj89** [comment]
Sorry @konstruktoid, I've misread that! That would be a useful feature though. I'll close this task as you've fixed the original issue. Thanks again :)
