### ISSUE TITLE
Typo causing check 2.6 to fail even with TLS enabled 

### ISSUE THREAD

**Issue by khba** [docker/docker-bench-security#312]
Hello, 

It seems like there is a tiny little typo on line 147 of file ./tests/docker-bench-security/tests/2_docker_daemon_configuration.sh :  instead of 

if get_docker_cumulative_command_line_args '--tlskey' | grep 'tlskey=' >/dev/null 2>&1; then

I think we should have : 

if get_docker_cumulative_command_line_args '--tlskey' | grep 'tlskey' >/dev/null 2>&1; then

ie without "=" because it makes the check fail. 

In my case I had the docker daemon running with these command lines: 

cat /proc/$PID/cmdline
/usr/bin/dockerd-Htcp://0.0.0.0:2376-Hunix:///var/run/docker.sock--storage-driveroverlay2--tlsverify--tlscacert/etc/docker/ca.pem--tlscert/etc/docker/server.pem--tlskey/etc/docker/server-key.pem--labelprovider=generic

in other terms with TLS enabled, but the check 2.6 kept failing with message "Docker daemon currently listening on TCP without TLS" , which obviously was not the case.

After checking where things were going wrong in the script, I fixed my problem by removing the "=".

**Comment by konstruktoid** [comment]
Closing since #313 has been merged.
