### ISSUE TITLE
Incorrect scoring on check 5.29?

### ISSUE THREAD

**Issue by introllo** [docker/docker-bench-security#316]
Check 5.29 - Ensure Docker's default bridge docker0 is not used

Here, we're looking at whether a container is running on the docker0 network.  In the CIS benchmark, this is listed as "(Not Scored)".

In the check, there is this assertion:

```
  if ! [ -z "$cName" ]; then
    info "     * Container in docker0 network: $cName"
    logjson "5.29" "INFO: $c"
```
shouldn't this be a "WARN" as the check has "failed" at this point?  Something like...

```  
  if ! [ -z "$cName" ]; then
    warn "     * Container in docker0 network: $cName"
    logjson "5.29" "WARN: $c"
```

Or, if we want to adhere to the Benchmark and consider this a "not scored" check, shouldn't the ending block be like...

```
  # We went through all the containers and found none in docker0 network
  if [ $fail -eq 0 ]; then
      pass "$check_5_29"
      logjson "5.29" "PASS"
      currentScore=$((currentScore + 1))
  else
      # Not scored, per Benchmark
      currentScore=$((currentScore - 0))
fi
```

Or, am I missing the logic here? Please advise.

**Comment by konstruktoid** [comment]
Hi @introllo, you're correct. Since this is a "not scored" test, `currentScore` shouldn't increase and it should be an `INFO`.
https://github.com/docker/docker-bench-security/blob/master/tests/5_container_runtime.sh#L1016-L1023 will be corrected.

**Comment by konstruktoid** [comment]
Closing since #322 has been merged.
