### ISSUE TITLE
Check 5.28 (PIDs limit) no longer valid for docker compose v3?

### ISSUE THREAD

**Issue by mwuerstl** [docker/docker-bench-security#319]
Under docker compose v3 there is no longer an option to set the pids_limit like there was in v2. Should this check be changed/removed or is there an alternate way to set a pids_limit for docker using compose v3? See https://github.com/docker/compose/issues/4792 for reference.
Thanks!

**Comment by konstruktoid** [comment]
Since you can set a pid limit when using the Docker client/server run command this is still a valid test.
https://docs.docker.com/compose/compose-file/compose-versioning/#version-3 contains info about cross-compatibility between Compose and the Docker Engine’s swarm mode.
Checking if the server is running in swarm mode is one thing but I don't believe there's a way to check if a container is started with docker-compose.

**Comment by m4d3bug** [comment]
> Since you can set a pid limit when using the Docker client/server run command this is still a valid test.
> 
> Checking if the server is running in swarm mode is one thing but I don't believe there's a way to check if a container is started with docker-compose.
> https://docs.docker.com/compose/compose-file/compose-versioning/#version-3 contains info about cross-compatibility between Compose and the Docker Engine’s swarm mode.
> 
> Will update the relevant tests when a new CIS benchmarks gets published.

Is there any other way to do the same?

**Comment by konstruktoid** [comment]
Setting a pid limit using compose? That option has not been introduced in version 3 (https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading) @m4d3bug

**Comment by konstruktoid** [comment]
Since you can't set a PID limit in version 3, this test will fail as intended.
https://github.com/docker/compose/issues/4792

**Comment by paulcalabro** [comment]
If it helps anyone else, I simply setup a hardening script to the side for items not supported by Docker Compose v3.

e.g.

```
docker container update --pids-limit=100 <container>
```

**Comment by paulcalabro** [comment]
@konstruktoid You could possibly check the labels for `com.docker.compose.*` to determine if the container was started using Docker Compose, however, I agree that it's still a valid test.

**Comment by pxds** [comment]
> If it helps anyone else, I simply setup a hardening script to the side for items not supported by Docker Compose v3.
> 
> e.g.
> 
> ```
> docker container update --pids-limit=100 <container>
> ```

Do you run that manually for each container? Have you found a way to automate that after running `docker-compose up -d`?
