### ISSUE TITLE
Check 5.1 - AppArmor not available on CentOS without kernel change.

### ISSUE THREAD

**Issue by mwuerstl** [docker/docker-bench-security#320]
Can check 5.1 be made optional for CentOS or is there an alternative to AppArmor protection that could be used?
Thanks!

**Comment by konstruktoid** [comment]
Hi @mwuerstl, `docker-bench-security`isn't really focused on specific distribution and 5.1 will fail on systems without AppArmor, just att `5.2  - Ensure SELinux security options are set, if applicable` will fail on Ubuntu by default. 
The difference is the wording and I'll report this to the Docker Benchmark upstream.

**Comment by konstruktoid** [comment]
The wording was updated in the CIS Benchmark on Aug 6, https://workbench.cisecurity.org/sections/36994/recommendations/103470/diff/201808060400.
