### ISSUE TITLE
JSON output contains multiple fields with the same key

### ISSUE THREAD

**Issue by makefu** [docker/docker-bench-security#323]
Hi,

it seems that the json output you are writing contains a dictionary with the same key multiple times. When parsing the file with `jq` some comments get lost because of the key overlap:

```json
{
  "4.6" : "WARN",
  "4.6" : "WARN: [jboss/base-jdk:8]",
  "4.6" : "WARN: [postgres:10.3]"
}
```
becomes
```json
{
  "4.6" : "WARN: [postgres:10.3]"
}
```

For reporting it would be nice if either the key "4.6" is only used once and is a dictionary itself or if the line is a list instead of a single key:
```json
{ 
  "4.6": { "containers": [ "postgres:10.3", "jboss/base-jdk:8" ], "title": "Ensure HEALTHCHECK ...", "result": "WARN" }
}
// OR //
[
 { "id": "4.6", "result": "WARN", "text": "" },
 { "id": "4.6", "result": "WARN", "text": "[postgres:10.3]" },
 { "id": "4.6", "result": "WARN", "text": "[jboss/base-jd:8]" },
]
```

**Comment by konstruktoid** [comment]
Hi @makefu and thanks for reporting this, #314 and #306 both contains updates to the json output and I'll have a look at both those PRs as soon as possble and hopefully fix this issue thereafter.

**Comment by makefu** [comment]
@konstruktoid that is great to hear! i only quickly checked in the issues for json output and forgot to check the Pull Requests.

Thanks for your efforts!

**Comment by konstruktoid** [comment]
Closing since #314 has been merged.
