### ISSUE TITLE
Check 3.18 misses valid "more restrictive" permissions

### ISSUE THREAD

**Issue by introllo** [docker/docker-bench-security#325]
Current code for 3.18 looks for 644 or 600 but misses 640.

Possible resolution on line 494...

From:
    if [ "$(stat -c %a $file)" -eq 644 -o "$(stat -c %a $file)" -eq 600 ]; then
To:
    if [ "$(stat -c %a $file)" -eq 644 -o "$(stat -c %a $file)" -eq 640 -o "$(stat -c %a $file)" -eq 600 ]; then

**Comment by konstruktoid** [comment]
Thanks @introllo, I've added the check to 3.18 in https://github.com/docker/docker-bench-security/pull/326.
