### ISSUE TITLE
Release images with version tags

### ISSUE THREAD

**Issue by mbode** [docker/docker-bench-security#329]
Currently https://hub.docker.com/r/docker/docker-bench-security/ only has a _latest_ tag. We use this image and ec7d8ce690bbd38b709b679d85857351c328db09 broke how we assert whether checks we want to succeed indeed do. Of course it was not hard to fix, but still it would be nice to be able to reference a specific version tag on docker hub.

**Comment by konstruktoid** [comment]
@diogomonica, v1.3.5 was just released, https://github.com/docker/docker-bench-security/releases/tag/v1.3.5, could you sign, add a `:latest` and a version tag to the image and publish it?

**Comment by konstruktoid** [comment]
Closing since we're all waiting for the Docker organization, and #405 includes the discussion regarding access to the Docker image key.
