### ISSUE TITLE
Does not complain for engine on TCP with no authentication

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker-bench-security#33]
I have opened my Docker host to the public internet without any TLS authentication:

```
$ ps aux | grep docker
root     55428  0.9  1.8 773376 65708 ?        Ssl  Jun11  52:40 /usr/bin/docker --daemon -H=unix:// -H=0.0.0.0:2375
```

and it didn't complain with any warnings or errors:

![image](https://cloud.githubusercontent.com/assets/159209/8164415/cb778b22-133d-11e5-8fd0-bb94b6bf94c3.png)

Not sure if that's a bug or by design, but I think `-H=ip` without `--tls**` must be a red flag of some sort.  I know there could be firewalls or other ACLs on top of the VM hosting the Docker engine, therefore it might be the safe(?).

Another dangerous option could be triggering an external service to call into this docker instance to figure out if it's really open to the internet w/o any auth...

**Comment by konstruktoid** [comment]
Thanks for the report, you're right we're not catching this.
`/usr/bin/docker --daemon -H=unix:// -H=0.0.0.0:2375`

```sh
$ sudo netstat -ltap|grep docker
tcp6       0      0 [::]:2375               [::]:*                  LISTEN      7633/docker
```

**Comment by konstruktoid** [comment]
#36 catches the unix:// as well, but a false positive is better.
