### ISSUE TITLE
Log command outputs in a file

### ISSUE THREAD

**Issue by upils** [docker/docker-bench-security#334]
Command outputs are only used to check values and are not logged.
A logging option to keep and review results would be great.

**Comment by upils** [comment]
Thanks for answering @konstruktoid 

I meant the output of commands used to check, like getting effective command line to launch the daemon or user executing container.
Many checks execute a docker command, grep wanted result and then throw the output in /dev/null. Sending this output to a file or even in the stdout could be very useful.

**Comment by konstruktoid** [comment]
I believe this would involved unnecessary amount of coding and is better resolved by manually removing the various `/dev/null` from the commands you find interesting.
