### ISSUE TITLE
Test result 7.4 does not showing.

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [docker/docker-bench-security#344]
When ever we run the bench-security it does not showing the result for 7.4 which is for 
"Ensure data exchanged between containers are encrypted on different nodes on the overlay network".
Also the 7.1 should be INFO instead of WARN as swarm is required in our environment so how do we fix it from WARN to PASS or should we ignore it ?

[INFO] 7 - Docker Swarm Configuration
[WARN] 7.1  - Ensure swarm mode is not Enabled, if not needed
[PASS] 7.2  - Ensure the minimum number of manager nodes have been created in a swarm
[WARN] 7.3  - Ensure swarm services are binded to a specific host interface
[INFO] 7.5  - Ensure Docker's secret management commands are used for managing secrets in a Swarm cluster
[PASS] 7.6  - Ensure swarm manager is run in auto-lock mode
[NOTE] 7.7  - Ensure swarm manager auto-lock key is rotated periodically
[INFO] 7.8  - Ensure node certificates are rotated as appropriate
[INFO] 7.9  - Ensure CA certificates are rotated as appropriate
[INFO] 7.10  - Ensure management plane traffic has been separated from data plane traffic

**Comment by boblington** [comment]
if you don't need 7.1, I recommend  ignoring it with -e option ie:
`sudo sh docker-bench-security.sh -e check_7_1`
I also submitted a PR that fixes missing 7.4 issue.

**Comment by dipanjanmukherjee83** [comment]
Thanks it is solved now.
