### ISSUE TITLE
Validation for ss and stat command not required

### ISSUE THREAD

**Issue by jondkent** [docker/docker-bench-security#354]
Hi,

The script docker-bench-security.sh has the following line:

req_progs='awk docker grep ss stat'

However 'ss' and 'stat' are not called within the script and I think these can be safely removed

Thanks,
Jon

**Comment by konstruktoid** [comment]
Hi @jondkent,
`ss` is used at https://github.com/docker/docker-bench-security/blob/master/tests/7_docker_swarm_configuration.sh#L66 and `stat` is used multiple times in https://github.com/docker/docker-bench-security/blob/master/tests/3_docker_daemon_configuration_files.sh.

**Comment by jondkent** [comment]
Ah, apols, did not see that

**Comment by konstruktoid** [comment]
No worries, have a great day 😄
