### ISSUE TITLE
exclude certain images from check

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [docker/docker-bench-security#369]
is it possible to exclude certain images from check. We have plenty of images for different kind of application and the problem is that for exclude only two or three images we have to listed out all the images using "-t" option. Is there any other way to exclude images from check. 
Thanks in advance.

**Comment by marksugar** [comment]
mark

**Comment by konstruktoid** [comment]
Hi @dipanjanmukherjee83 and @marksugar, currently there's no other way, but I'll add an option similar to `-x EXCLUDE` as soon as possible.

**Comment by konstruktoid** [comment]
Closed thanks to #390
