### ISSUE TITLE
README incorrect for quick start.

### ISSUE THREAD

**Issue by xamox** [docker/docker-bench-security#37]
It appears 2 days ago it was changed to docker-bench-security, to pull from docker hub.  This container does not exists on docker hub so this is broken at the moment.

docker run -it --net host --pid host --cap-add audit_control \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /etc:/etc --label docker-bench-security \
    docker-bench-security

**Comment by diogomonica** [comment]
Fixed by adding diogomonica/docker-bench-security. I have to add this as an official image later on.
