### ISSUE TITLE
/usr/bin not mounted inside container

### ISSUE THREAD

**Issue by src7** [docker/docker-bench-security#371]
Hello,

surely because there was no very nice ways to do this, /usr/bin is not mounted inside the container. So files tested in this directory are always not found (docker-containerd and docker-runc) and no warnings are ever displayed for 1.12 and 1.13.

Actually, to solve the issue I run the container with : 
```
    -v /usr/bin/docker-containerd:/usr/bin/docker-containerd \
    -v /usr/bin/docker-runc:/usr/bin/docker-runc \
```

PS : I know using default large auditing (especially on something like /var/lib/docker) will generate so much logs it won't really be taken seriously by admins.

**Comment by src7** [comment]
Hi @konstruktoid,

in fact the script check the rules only if the file is found (and it works perfectly if ti is).

https://github.com/docker/docker-bench-security/blob/f791eb8a7047fadeb7bd742312c28999478c916f/tests/1_host_configuration.sh#L350

https://github.com/docker/docker-bench-security/blob/f791eb8a7047fadeb7bd742312c28999478c916f/tests/1_host_configuration.sh#L387

**Comment by konstruktoid** [comment]
Thanks @src7, I'll update the readme.

**Comment by src7** [comment]
No problem
