### ISSUE TITLE
Exclude containers switch

### ISSUE THREAD

**Issue by jammasterj89** [docker/docker-bench-security#383]
Hi,

When trying to exclude some containers using the -x switch they are still being reported on in some checks (4.6 and 4.9) but have been correctly excluded from such checks as 5.10 - 5.13, so it is partially working.

To reproduce (basically run docker bench against the only nginx container on the server and exclude all wazuh containers):

    $ docker images
    REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
    nginx                          latest              719cd2e3ed04        7 days ago          109MB
    docker/docker-bench-security   latest              0037349aef7e        4 months ago        51.6MB
    wazuh/wazuh-kibana             3.7.0_6.5.0         42a2a0b98b02        6 months ago        1.3GB
    wazuh/wazuh-logstash           3.7.0_6.5.0         632e0c21f29c        6 months ago        702MB
    wazuh/wazuh                    3.7.0_6.5.0         592bdc949177        6 months ago        1.05GB

    $ docker run -it --net host --pid host --userns host --cap-add audit_control \
    -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
    -v /etc:/etc \
    -v /usr/bin/docker-containerd:/usr/bin/docker-containerd \
    -v /usr/bin/docker-runc:/usr/bin/docker-runc \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --label docker_bench_security \
    docker/docker-bench-security -x wazuh_kibana_1,wazuh_wazuh_1,wazuh_logstash_1

    trimmed output...
    [INFO] 4 - Container Images and Build File
    [INFO] 4.1  - Ensure a user for the container has been created
    [INFO]      * No containers running
    [NOTE] 4.2  - Ensure that containers use trusted base images
    [NOTE] 4.3  - Ensure unnecessary packages are not installed in the container
    [NOTE] 4.4  - Ensure images are scanned and rebuilt to include security patches
    [WARN] 4.5  - Ensure Content trust for Docker is Enabled
    [WARN] 4.6  - Ensure HEALTHCHECK instructions have been added to the container image
    [WARN]      * No Healthcheck found: [nginx:latest]
    [WARN]      * No Healthcheck found: [wazuh/wazuh-kibana:3.7.0_6.5.0]
    [WARN]      * No Healthcheck found: [wazuh/wazuh-logstash:3.7.0_6.5.0]
    [WARN]      * No Healthcheck found: [wazuh/wazuh:3.7.0_6.5.0]
    [INFO] 4.7  - Ensure update instructions are not use alone in the Dockerfile
    [INFO]      * Update instruction found: [wazuh/wazuh-kibana:3.7.0_6.5.0]
    [INFO]      * Update instruction found: [wazuh/wazuh-logstash:3.7.0_6.5.0]
    [NOTE] 4.8  - Ensure setuid and setgid permissions are removed in the images
    [INFO] 4.9  - Ensure COPY is used instead of ADD in Dockerfile
    [INFO]      * ADD in image history: [nginx:latest]
    [INFO]      * ADD in image history: [docker/docker-bench-security:latest]
    [INFO]      * ADD in image history: [wazuh/wazuh-kibana:3.7.0_6.5.0]
    [INFO]      * ADD in image history: [wazuh/wazuh-logstash:3.7.0_6.5.0]
    [INFO]      * ADD in image history: [wazuh/wazuh:3.7.0_6.5.0]
    [NOTE] 4.10  - Ensure secrets are not stored in Dockerfiles
    [NOTE] 4.11  - Ensure verified packages are only Installed
    ...

------

Interestingly if I try to use the -t flag to explicitly test the nginx container only, the wazuh containers are also returned in the 5.x tests e.g. 5.2 - 5.28

    $ docker run -it --net host --pid host --userns host --cap-add audit_control \
    -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
    -v /etc:/etc \
    -v /usr/bin/docker-containerd:/usr/bin/docker-containerd \
    -v /usr/bin/docker-runc:/usr/bin/docker-runc \
    -v /usr/lib/systemd:/usr/lib/systemd \
    -v /var/lib:/var/lib \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --label docker_bench_security \
    docker/docker-bench-security -t nginx

    trimmed output...
    [INFO] 5 - Container Runtime
    [PASS] 5.1  - Ensure AppArmor Profile is Enabled
    [WARN] 5.2  - Ensure SELinux security options are set, if applicable
    [WARN]      * No SecurityOptions Found: wazuh_kibana_1
    [WARN]      * No SecurityOptions Found: wazuh_wazuh_1
    [WARN]      * No SecurityOptions Found: wazuh_logstash_1
    [PASS] 5.3  - Ensure Linux Kernel Capabilities are restricted within containers
    [PASS] 5.4  - Ensure privileged containers are not used
    [PASS] 5.5  - Ensure sensitive host system directories are not mounted on containers
    [PASS] 5.6  - Ensure ssh is not run within containers
    [WARN] 5.7  - Ensure privileged ports are not mapped within containers
    [WARN]      * Privileged Port in use: 514 in wazuh_wazuh_1
    [NOTE] 5.8  - Ensure only needed ports are open on the container
    [PASS] 5.9  - Ensure the host's network namespace is not shared
    [WARN] 5.10  - Ensure memory usage for container is limited
    [WARN]      * Container running without memory restrictions: wazuh_kibana_1
    [WARN]      * Container running without memory restrictions: wazuh_wazuh_1
    [WARN]      * Container running without memory restrictions: wazuh_logstash_1
    [WARN] 5.11  - Ensure CPU priority is set appropriately on the container
    [WARN]      * Container running without CPU restrictions: wazuh_kibana_1
    [WARN]      * Container running without CPU restrictions: wazuh_wazuh_1
    [WARN]      * Container running without CPU restrictions: wazuh_logstash_1
    [WARN] 5.12  - Ensure the container's root filesystem is mounted as read only
    [WARN]      * Container running with root FS mounted R/W: wazuh_kibana_1
    [WARN]      * Container running with root FS mounted R/W: wazuh_wazuh_1
    [WARN]      * Container running with root FS mounted R/W: wazuh_logstash_1
    [WARN] 5.13  - Ensure incoming container traffic is binded to a specific host interface
    [WARN]      * Port being bound to wildcard IP: 0.0.0.0 in wazuh_wazuh_1
    [WARN]      * Port being bound to wildcard IP: 0.0.0.0 in wazuh_wazuh_1
    [WARN]      * Port being bound to wildcard IP: 0.0.0.0 in wazuh_wazuh_1
    [WARN]      * Port being bound to wildcard IP: 0.0.0.0 in wazuh_wazuh_1
    [WARN]      * Port being bound to wildcard IP: 0.0.0.0 in wazuh_logstash_1
    [WARN] 5.14  - Ensure 'on-failure' container restart policy is set to '5'
    [WARN]      * MaximumRetryCount is not set to 5: wazuh_kibana_1
    [WARN]      * MaximumRetryCount is not set to 5: wazuh_wazuh_1
    [WARN]      * MaximumRetryCount is not set to 5: wazuh_logstash_1
    [PASS] 5.15  - Ensure the host's process namespace is not shared
    [PASS] 5.16  - Ensure the host's IPC namespace is not shared
    [PASS] 5.17  - Ensure host devices are not directly exposed to containers
    [INFO] 5.18  - Ensure the default ulimit is overwritten at runtime, only if needed
    [INFO]      * Container no default ulimit override: wazuh_kibana_1
    [INFO]      * Container no default ulimit override: wazuh_wazuh_1
    [INFO]      * Container no default ulimit override: wazuh_logstash_1
    [PASS] 5.19  - Ensure mount propagation mode is not set to shared
    [PASS] 5.20  - Ensure the host's UTS namespace is not shared
    [PASS] 5.21  - Ensure the default seccomp profile is not Disabled
    [NOTE] 5.22  - Ensure docker exec commands are not used with privileged option
    [NOTE] 5.23  - Ensure docker exec commands are not used with user option
    [PASS] 5.24  - Ensure cgroup usage is confirmed
    [WARN] 5.25  - Ensure the container is restricted from acquiring additional privileges
    [WARN]      * Privileges not restricted: wazuh_kibana_1
    [WARN]      * Privileges not restricted: wazuh_wazuh_1
    [WARN]      * Privileges not restricted: wazuh_logstash_1
    [WARN] 5.26  - Ensure container health is checked at runtime
    [WARN]      * Health check not set: wazuh_kibana_1
    [WARN]      * Health check not set: wazuh_wazuh_1
    [WARN]      * Health check not set: wazuh_logstash_1
    [INFO] 5.27  - Ensure docker commands always get the latest version of the image
    [WARN] 5.28  - Ensure PIDs cgroup limit is used
    [WARN]      * PIDs limit not set: wazuh_kibana_1
    [WARN]      * PIDs limit not set: wazuh_wazuh_1
    [WARN]      * PIDs limit not set: wazuh_logstash_1
    [PASS] 5.29  - Ensure Docker's default bridge docker0 is not used
    [PASS] 5.30  - Ensure the host's user namespaces is not shared
    [PASS] 5.31  - Ensure the Docker socket is not mounted inside any containers
    ...
Apologies if I am missing something.

**Comment by konstruktoid** [comment]
Hi @jammasterj89 and thanks for reporting this, I'll have a look at it as soon as possible.

**Comment by jammasterj89** [comment]
Hi @konstruktoid 

I have had a quick look at this myself. I think this issue comes down to my misreading of the usage. So it looks like you can include or exclude containers, but you cannot exclude images, only include them. I think the fix would be to add another flag to exclude images, but this probably doesn't make much sense (I may be wrong!) as I would assume if someone wanted to exclude a container then they probably want to exclude its image as well.

Instead of adding another flag I think the simpler approach would be to change the include and exclude flags to cover both containers and images. This allows a user to enter some greppable input that can match containers and images, so in the above case "-x wazuh or -i wazuh" would exclude/include matching containers and images. I have made this changes in a forked repo here:

https://github.com/jammasterj89/docker-bench-security

Happy to make a PR if you agree with the changes.

Thanks!

**Comment by konstruktoid** [comment]
Thanks again @jammasterj89, and sorry for the late reply. Could you please create a PR, it's easier to work it.

**Comment by jammasterj89** [comment]
@konstruktoid no problem, have done with PR 390.

Thanks!
