### ISSUE TITLE
discussion: does it really make sense to suggest disabling ICC?

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker-bench-security#388]
https://github.com/docker/docker-bench-security/blob/55ab78bb1248c71b03c783d784b34afee7ac0d0b/tests/2_docker_daemon_configuration.sh#L12-L33

CIS 2.1 suggests disabling ICC, but I'm not sure it really makes sense to harden the network, because disabling ICC doesn't block raw Ethernet packets (unless `--cap-drop net_raw` is explicitly specified): https://github.com/moby/moby/issues/36355

Also, disabling ICC is known to break Docker EE: https://success.docker.com/article/can-i-disable-inter-container-communication-icc-in-docker-ee

**Comment by konstruktoid** [comment]
Hi @AkihiroSuda, and sorry for the late reply.
There's a new CIS Docker Benchmark (released in july), but I haven't had time to go through all the changes and updates yet.

**Comment by AkihiroSuda** [comment]
The new version still suggests disabling ICC

**Comment by konstruktoid** [comment]
Thanks, I'll push https://github.com/moby/moby/issues/36355 to CIS.
Meanwhile I will follow the benchmark as expected, and if your organization needs `ICC` I sugguest you just ignore the script output regarding that test.

**Comment by raesene** [comment]
Hi Both, 

So from the CIS benchmark perspective, there's a couple of things from this.

It sounds like we need to update the Impact section to note that setting `--icc=false` is not supported under Docker EE.

We also need to note that setting `--icc=false` is not a fully effective control, unless all containers attached to that bridge have dropped CAP_NET_RAW.  (That is in there as a recommendation, but it sounds like it's work calling out specifically here, to emphasize  that both need to be set to be effective)

Does that sound like it would address things?

**Comment by konstruktoid** [comment]
Yeah, I believe that would address it @raesene

**Comment by AkihiroSuda** [comment]
yes, thanks
