### ISSUE TITLE
1.2.1 "Ensure a separate partition for containers has been created" doesn't work with userns

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker-bench-security#394]
https://github.com/docker/docker-bench-security/blob/6d73492aab235840aa134878a079d6e4da328eed/tests/1_host_configuration.sh#L68-L86

This check fails when `/var/lib/docker` has a dedicated partition but `userns-remap` is enabled, because `.DockerRootDir` is like `/var/lib/docker/296608.296608`, not `/var/lib/docker`

**Comment by konstruktoid** [comment]
Duplicate of https://github.com/docker/docker-bench-security/issues/332
