### ISSUE TITLE
Plan for new release?

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker-bench-security#396]
v1.3.3 was released two years ago.
https://github.com/docker/docker-bench-security/releases

Is there any plan to ship a new release?

**Comment by konstruktoid** [comment]
Hi @AkihiroSuda, yeah v1.3.3 was release two years ago but the latest CIS benchmark was released in july and it seems 1.3.4 never got made into Docker image...

https://github.com/docker/docker-bench-security/commit/227f2faa5b92930c67a0c91f74c1eabaedcaae03#diff-3fb01832c41e63e84695c76e31a8e0f9

A new Docker image and official release will be published after additional testing.

**Comment by konstruktoid** [comment]
v1.3.5 released: https://github.com/docker/docker-bench-security/releases/tag/v1.3.5

**Comment by AkihiroSuda** [comment]
thanks!
