### ISSUE TITLE
Test 4.9 fails to detect ADD instruction

### ISSUE THREAD

**Issue by anass114** [docker/docker-bench-security#399]
Hi, 
I'm running the script in Debian image and this test doesn't detect ADD instructions 
`if docker history --format "{{ .CreatedBy }}" --no-trunc "$img" | \
      sed '$d' | grep -q 'ADD'; then`

Maybe it should be replaced by : 
`if docker history --format "{{ .CreatedBy }}" --no-trunc "$img" | \
      sed "$d" | grep -q 'ADD'; then`

Before modification
![image](https://user-images.githubusercontent.com/15892444/66213792-c2557300-e6c0-11e9-975d-a7949853a3b9.png)

After modification
![image](https://user-images.githubusercontent.com/15892444/66213754-b1a4fd00-e6c0-11e9-9f59-038ad085534a.png)

**Comment by konstruktoid** [comment]
Hi @anass114, I can't see any difference between the two commands in your issue and I believe the current test works as intended.

```
$ docker history --format "{{ .CreatedBy }}" --no-trunc $(docker images -q alpine:latest)
/bin/sh -c #(nop)  CMD ["/bin/sh"]
/bin/sh -c #(nop) ADD file:fe64057fbb83dccb960efabbf1cd8777920ef279a7fa8dbca0a8801c651bdf7c in / 
$ docker history --format "{{ .CreatedBy }}" --no-trunc $(docker images -q alpine:latest) | sed "$d" | grep -q 'ADD'
```

**Comment by anass114** [comment]
Hi, 

Well in fact I Don't really understant why you use `sed '$d'`
The response from this command `docker history --format "{{ .CreatedBy }}" --no-trunc $(docker images -q alpine:latest)` will you give you : 
`/bin/sh -c #(nop)  CMD ["/bin/sh"]
/bin/sh -c #(nop) ADD file:fe64057fbb83dccb960efabbf1cd8777920ef279a7fa8dbca0a8801c651bdf7c in /`

If you use sed on this response, it will delete the last line with the ADD instruction, so when grep will search for any ADD pattern, it will found nothing and it will pass the test

**Comment by anass114** [comment]
In debian, for some Reason `sed "$d"` does Nothing :
`root@jessie:/home/vagrant/tets/docker-bench-security# docker history --format "{{ .CreatedBy }}" --no-trunc $(docker images -q alpine:latest) | sed "$d"
/bin/sh -c #(nop)  CMD ["/bin/sh"]
/bin/sh -c #(nop) ADD file:fe64057fbb83dccb960efabbf1cd8777920ef279a7fa8dbca0a8801c651bdf7c in /
root@jessie:/home/vagrant/tets/docker-bench-security# docker history --format "{{ .CreatedBy }}" --no-trunc $(docker images -q alpine:latest) | sed '$d'
/bin/sh -c #(nop)  CMD ["/bin/sh"]
`

**Comment by konstruktoid** [comment]
My bad, it should of course be `'$d'`,`"$d"` is empty.

> If you use sed on this response, it will delete the last line with the ADD instruction, so when grep will search for any ADD pattern, it will found nothing and it will pass the test.

Yes, and that's the point unless proven wrong. Many baseimages adds the file system as a `.tgz|.tar.gz`. See for example https://github.com/alpinelinux/docker-alpine/blob/v3.10/x86_64/Dockerfile or https://github.com/debuerreotype/docker-debian-artifacts/blob/dist-amd64/buster/Dockerfile.

**Comment by anass114** [comment]
Okay, well my bad, sorry for the inconvenience

**Comment by konstruktoid** [comment]
No worries 👍
