### ISSUE TITLE
[dumb-init] docker-bench-security.sh: No such file or directory

### ISSUE THREAD

**Issue by ahteck** [docker/docker-bench-security#422]
Hi,

I saw someone else raised this issue before, but there are no solution to this issue.
Can anyone advise what should I check in my Docker Toolbox?

![image](https://user-images.githubusercontent.com/27942400/78628750-aa58e900-78c7-11ea-914a-aefa1ccbbf0a.png)

**Comment by konstruktoid** [comment]
Hi @ahteck, are you building a local copy or using the available image? Have you tried running the shell script?
And it seems that is a Windows shell you're running?

**Comment by ahteck** [comment]
> Hi @ahteck, are you building a local copy or using the available image? Have you tried running the shell script?
> And it seems that is a Windows shell you're running?

I have built a local copy.
Yes, I am running on Docker Toolbox in Windows 10
https://docs.docker.com/toolbox/toolbox_install_windows/

![image](https://user-images.githubusercontent.com/27942400/78639348-5d354100-78e0-11ea-860c-cedeede3542d.png)
This is the result when I ran the script

**Comment by konstruktoid** [comment]
I haven't tested on Windows 10, but let's try it.

First, it seems you're missing the `ss` command.

```
$ dpkg -S /bin/ss 
iproute2: /bin/ss
```

**Comment by IrmantasM** [comment]
I'm getting same error on macOS Mojave 10.14.6:

```
$ docker run -it --net host --pid host --userns host --cap-add audit_control \
>     -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
>     -v /etc:/etc \
>     -v /usr/local/bin:/usr/local/bin:ro \
>     -v /var/lib:/var/lib:ro \
>     -v /var/run/docker.sock:/var/run/docker.sock:ro \
>     --label docker_bench_security \
>     docker/docker-bench-security
[dumb-init] docker-bench-security.sh: No such file or directory
$
$
$ docker -v
Docker version 19.03.8, build afacb8b
```

Same error when building and running locally.

**Comment by konstruktoid** [comment]
Hi there @IrmantasM, I incorrectly added `-v /usr/local/bin:/usr/local/bin:ro` to the `README`.
Will fix.

**Comment by konstruktoid** [comment]
I believe this is fixed in https://github.com/docker/docker-bench-security/pull/429

**Comment by IrmantasM** [comment]
Thanks @konstruktoid, it works fine now!

**Comment by ahteck** [comment]
Able to run pre-built container
Closing this issue
