### ISSUE TITLE
containerd and runc audit checks use the wrong path

### ISSUE THREAD

**Issue by illyaMs** [docker/docker-bench-security#424]
Hi everyone (and thanks for doing a great job for community by maintainting this project and contrubuting to it)!

**Problem**:
The following checks:
* `1.2.11 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd`
* `1.2.12 Ensure auditing is configured for Docker files and directories - /usr/sbin/runc`
are looking for the `containerd` and `runc` audit entries, supposing that the files themselves may be found under `/usr/bin/containerd/` and `/usr/sbin/runc` folders, respectively.

However, those files may also be found under `/usr/bin/docker-containerd` and `/usr/bin/docker-runc`, respectively. (My guess it depends on docker version and/or OS). Also in [documentation section](https://github.com/docker/docker-bench-security/blob/master/README.md#running-docker-bench-for-security) the suggested container mounts are `/usr/bin/docker-containerd` and `/usr/bin/docker-runc`.

**Possible solutions:**
1. Use a `/usr/bin/docker-containerd`/`/usr/bin/runc` as fallback paths in `1.2.11` & `1.2.12` tests
2. Somehow resolve this path dynamically in both tests

**Comment by konstruktoid** [comment]
Hi @illyaMs, you're absolutely correct.
This is because the test is based on the CIS Docker Benchmark which states `1.2.11 Ensure auditing is configured for Docker files and directories -/usr/bin/containerd (Scored)` and `1.2.12 Ensure auditing is configured for Docker files and directories -/usr/sbin/runc (Scored)`, so the script is forced to include it.

I'll go through  various distros and push a change to the upstream CIS Benchmark and it will trickle down into this script eventually.

**Comment by illyaMs** [comment]
Cool, thanks for the quick feedback, @konstruktoid (and for your efforts, for sure).

**Comment by konstruktoid** [comment]
@illyaMs, on which distributions/OS:es are the files named `docker-containerd` and `docker-runc`?

```
$ for x in $(vagrant status | grep 'running.*virtualbox' | awk '{print $1}' | grep -vE '^$|focal'); do echo "$x:" && vagrant ssh "$x" -c 'command -v containerd runc docker-containerd docker-runc && echo' 2>/dev/null; done
bionic:
/usr/bin/containerd
/usr/bin/runc

buster:
/usr/bin/containerd
/usr/bin/runc

centos:
fedora:
/usr/bin/containerd
/usr/bin/runc
```

`centos` failed with the following:
```
[vagrant@centos ~]$ curl -sSL get.docker.com | sh
# Executing docker install script, commit: 442e66405c304fa92af8aadaa1d9b31bf4b0ad94
+ sudo -E sh -c 'yum install -y -q yum-utils'
+ sudo -E sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sudo -E sh -c 'yum makecache'
CentOS-8 - AppStream                                                                                                                                                  21 kB/s | 4.3 kB     00:00    
CentOS-8 - Base                                                                                                                                                      7.5 kB/s | 3.8 kB     00:00    
CentOS-8 - Extras                                                                                                                                                    6.7 kB/s | 1.5 kB     00:00    
Docker CE Stable - x86_64                                                                                                                                             15 kB/s | 3.5 kB     00:00    
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                                                                49 kB/s |  34 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                        54 kB/s |  33 kB     00:00    
Metadata cache created.
+ '[' -n '' ']'
+ sudo -E sh -c 'yum install -y -q docker-ce'
Error: 
 Problem: package docker-ce-3:19.03.8-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package containerd.io-1.2.10-3.2.el7.x86_64 is excluded
  - package containerd.io-1.2.13-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.3.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.el7.x86_64 is excluded
  - package containerd.io-1.2.4-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.5-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.6-3.3.el7.x86_64 is excluded
```

**Comment by konstruktoid** [comment]
Seems the `README` is wrong as well.

**Comment by konstruktoid** [comment]
I've update the CIS Docker Benchmark draft:
`1.1.12 Ensure auditing is configured for Docker files and directories - /usr/bin/runc`

**Comment by illyaMs** [comment]
@konstruktoid not sure about the whole list of distributions, but at least these paths are different under the following configuration:
```bash
# echo $OSTYPE
linux-gnu
# lsb_release -rd
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
# uname -r
4.15.0-76-generic
```

I've just ran part of your command on one of such clusters and here's the result:
```bash
# command -v containerd runc docker-containerd docker-runc
/usr/bin/docker-containerd
/usr/bin/docker-runc
```

**Comment by konstruktoid** [comment]
@illyaMs are those installed with `curl -sSL get.docker.com | sh` or the available repo packages?

**Comment by illyaMs** [comment]
@konstruktoid Double-checked with my colleagues, been told that the installation has been done via a  simple `apt install docker.io` command.

**Comment by konstruktoid** [comment]
That's what I thought @illyaMs, I believe we had a related issue earlier but I can't find it at the moment.
Debian-family `docker.io` vs `docker` (the KDE3/GNOME2 applet) naming is kind of messy.

I suggest following https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions.

**Comment by illyaMs** [comment]
Thanks for the link, @konstruktoid .

Just to make things 100% clear, do I get it right that the old version of docker package (`docker.io`) is the root cause of the issue? (And though by following the update instructions you've mentioned above we'll have the `runc` and `containerd` under the paths expected by `docker-bench`?)

**Comment by konstruktoid** [comment]
Yes that is mostly correct @illyaMs.
As we both pointed out in this thread, the CIS Benchmark is out-of-date regarding `1.2.12 Ensure auditing is configured for Docker files and directories -/usr/sbin/runc` and I've submitted an update.

**Comment by illyaMs** [comment]
Thanks for clarification.
Ok then, so I guess the issue may be closed (or shall we keep it open for a while and wait till your `1.2.12` correction is approved/added)?

**Comment by konstruktoid** [comment]
Let's keep it open as it's still an issue until the next benchmark arrives.

**Comment by konstruktoid** [comment]
Closing since the CIS Docker Benchmark and https://github.com/docker/docker-bench-security/blob/3769a64a2f18daab9718352a15dfb4d3041ac168/tests/1_host_configuration.sh#L583-L615 now contains `/usr/bin/runc`
