### ISSUE TITLE
Dockerfile for opensuse doesn't seem to work

### ISSUE THREAD

**Issue by karthiksiva-github** [docker/docker-bench-security#425]
Hi,

1) Dockerfile.opensuse doesn't seem to work since the base image "opensuse"is deprecated. Either we will have to use opensuse/leap and opensuse/tumbleweed whichever is appropriate.
2) awk is no more part of opensuse and is deprecated .Can the script be modified to use gawk instead of awk.

Thanks,
Karthik

**Comment by konstruktoid** [comment]
Thanks @karthiksiva-github for opening this issue, I will have a look at it as soon as possible.

**Comment by konstruktoid** [comment]
I believe this has been fixed with #427
