### ISSUE TITLE
Running security bench: Cannot reach trust server at this time

### ISSUE THREAD

**Issue by rirlswift** [docker/docker-bench-security#431]
I am running the security bench per the documentation for Ubuntu
```sh
docker run -it --net host --pid host --userns host --cap-add audit_control \
    -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
    -v /etc:/etc:ro \
    -v /lib/systemd/system:/lib/systemd/system:ro \
    -v /usr/bin/containerd:/usr/bin/containerd:ro \
    -v /usr/bin/runc:/usr/bin/runc:ro \
    -v /usr/lib/systemd:/usr/lib/systemd:ro \
    -v /var/lib:/var/lib:ro \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    --label docker_bench_security \
    docker/docker-bench-security
```
I get this output: 
```
docker: unable to reach trust server at this time: 500.
See 'docker run --help'.
```
Is there something I am missing? Do I need to setup the DTR per [here](https://docs.docker.com/ee/dtr/user/access-dtr/)

I'd truly appreciate any help or suggestions or guidance.

**Comment by konstruktoid** [comment]
Hi @rirlswift, are you running the officail Docker image, or have you built your own?
If you're using the official image, could you please try running the script on the host or build your own image?

**Comment by rirlswift** [comment]
Hey  konstruktoid,
Thanks for helping me get this to work. I am now running the script on the host via
```
git clone https://github.com/docker/docker-bench-security.git
cd docker-bench-security
sudo sh docker-bench-security.sh
```
Looks great, even on CE.

**Comment by konstruktoid** [comment]
ref https://github.com/docker/docker-bench-security/issues/405
