### ISSUE TITLE
The image on Docker Hub is outdated

### ISSUE THREAD

**Issue by HristoStoyanovMM** [docker/docker-bench-security#433]
Hi guys, 

It made me impression that the official docker image referenced by the README is 1 year old... It might be helpful if you rebuild it with the latest version.
I suppose you guys know better than anyone, that git commits could automatically trigger Docker Hub automated builds :)

On an unrelated note, it might also be valuable to add **CIS Level 1 only** check functions. Something like:
`container_images_level1() {
  check_4
  check_4_1
  check_4_2
  check_4_3
  check_4_4
  check_4_6
  check_4_7
  check_4_9
  check_4_10
  check_4_end
}`
Do you like the idea? If I add a PR for this, would that get merged?

Best Regards
Hristo Stoyanov

**Comment by konstruktoid** [comment]
Hi @HristoStoyanovMM, and you're absolutely correct.
See https://github.com/docker/docker-bench-security/issues/405 for more information.

**Comment by HristoStoyanovMM** [comment]
Hi @konstruktoid , thanks for the quick response.
Let's hope that the updated and signed image will be pushed soon.

What do you think about my proposal for adding **level 1 only** check functions?

**Comment by konstruktoid** [comment]
Sorry I missed that part somehow, a level 1 only function with be great. Feel free to submit a PR.

**Comment by konstruktoid** [comment]
Closing since we're all waiting for the Docker organization.
