### ISSUE TITLE
-it options in recommended run commands for prebuilt container

### ISSUE THREAD

**Issue by dylanzt** [docker/docker-bench-security#452]
Hi, I'm curious if there's any particular reason why the recommended run commands for the prebuilt container in the README include the -it flags. We're trying to use this tool in a CI environment where we can't set those flags, and omitting them doesn't seem to have any impact on the operation or output of the tool. It doesn't seem necessary to run interactively.

**Comment by konstruktoid** [comment]
Hi @dylanzt and thanks for that good question. In all honesty it might just be a 3 year old leftover because, as you said, the container works without `-it`.

**Comment by konstruktoid** [comment]
@dylanzt, the README has been updated.

**Comment by dylanzt** [comment]
Thanks @konstruktoid, missed this earlier. LGTM, cheers for the response.
