### ISSUE TITLE
Different behaviour for pgrep between version 3.3.3-3 (Debian 7) and 3.3.9-1ubuntu2.2 (Ubuntu 14.04)

### ISSUE THREAD

**Issue by jlusiardi** [docker/docker-bench-security#47]
Hey guys,

i tried to execute your script on a Ubuntu 14.04 host and learned that pgrep from the procps tools (version 3.3.9-1ubuntu2.2) shipped with that distro changed it behaviour.

For example, taken from your script (2_docker_daemon_configuration.sh line 8)
```bash
pgrep -lf docker | grep lxc >/dev/null 2>&1
```
In version **3.3.3-3** the result of "*pgrep -lf docker*" looks like "*2086 /usr/bin/docker -d -p /var/run/docker.pid*" which is perfect for the piped greps.

In version **3.3.9-1ubuntu2.2** the result of "*pgrep -lf docker*" looks just like "*910 docker*" where as "*pgrep -alf docker*" returns  the desired information (e.g. "*910 /usr/bin/docker -d --icc=false*") again.

This breaks all tests that use pgrep for the new version.

Please have a look to improve the script for Ubuntu Users

Thanks!

Joachim

**Comment by konstruktoid** [comment]
Thanks @jlusiardi.
Closing this because of merge of #48.
