### ISSUE TITLE
"[dumb-init] docker-bench-security.sh: No such file or directory" on Windows 10 when trying to build locally

### ISSUE THREAD

**Issue by pxds** [docker/docker-bench-security#470]
After reading #422 and not seeing a solution for Windows, I kept getting that error until I changed the Dockerfile, adding "sh" to the ENTRYPOINT and it worked. Is that a proper way to buil/drun this container?

`ENTRYPOINT [ "/usr/bin/dumb-init", "sh", "docker-bench-security.sh" ]`

**Comment by konstruktoid** [comment]
Hi @pxds, I haven't tested it on Windows but as long as you don't get any errors and everything seems to work, then it's a proper way :)

**Comment by pxds** [comment]
Hehe then consider it proper :)
