### ISSUE TITLE
Invalid check for socket existence

### ISSUE THREAD

**Issue by drmaciej** [docker/docker-bench-security#477]
In multiple places existence of a socket file is checked with `-f` instead of `-S`. This results in _File not found_ across a few places, like 3.23 and 3.24.

**Comment by konstruktoid** [comment]
Hi @drmaciej and thank you for creating this issue, can you please verify #478 ?

**Comment by drmaciej** [comment]
Hi @konstruktoid, thanks for a quick fix. https://github.com/docker/docker-bench-security/pull/478 looks good to me!
