### ISSUE TITLE
rootless

### ISSUE THREAD

**Issue by xoroz** [docker/docker-bench-security#505]
Any chance to have a version for docker setup with rootless mode?

Since docker 20.10 rootless mode is no longer experimental, and its production ready.
https://docs.docker.com/engine/security/rootless/

Thank you

**Comment by konstruktoid** [comment]
Hi @xoroz, yeah that makes sense.
I'll have a look at it and try to align it with the next CIS release.

**Comment by xoroz** [comment]
any news on this?
Thanks

**Comment by konstruktoid** [comment]
Hi again @xoroz, the latest CIS benchmark doesn't account for rootless mode.
