### ISSUE TITLE
404: functions_lib.sh link is invalid

### ISSUE THREAD

**Issue by Wenzel** [docker/docker-bench-security#507]
While reading the documentation on this container on Docker hub:
https://hub.docker.com/r/docker/docker-bench-security

![image](https://user-images.githubusercontent.com/964610/206672754-b8e8ad3a-fffd-44c9-a0e8-8822451b62cf.png)

The link for [functions_lib.sh](https://hub.docker.com/r/docker/functions_lib.sh) is invalid

![image](https://user-images.githubusercontent.com/964610/206673201-ec1507b3-cfbc-462b-bb7a-b6fd8a4e6474.png)

**Comment by konstruktoid** [comment]
That link isn’t present on https://github.com/docker/docker-bench-security, and you shouldn't use the image available there since it's so out-of-date. See https://github.com/docker/docker-bench-security/issues/405.
