### ISSUE TITLE
allow disabling on a rule-by-rule basis

### ISSUE THREAD

**Issue by NathanMcCauley** [docker/docker-bench-security#51]
Some folks might like to disable rules on a case by case basis.

**Comment by b-long** [comment]
:+1:

**Comment by skelethan** [comment]
Yes please!  This will help large organizations filter out noise and focus on the rules that are most important to them.

**Comment by konstruktoid** [comment]
Sorry for the late reply @NathanMcCauley, but we're planning to rewrite the script and when doing so add support for individual and grouped tests.

**Comment by diogomonica** [comment]
What me and @konstruktoid were thinking of doing was the ability of supporting different Profiles. Companies could reuse the current tests and selectively add/remove tests from any of the base profiles, and maybe even contribute them back to dockerbench.com.

**Comment by skelethan** [comment]
That's even better, will help as we bring more groups from our company onto Docker - each group can configure their own profile.

**Comment by rtrauntvein** [comment]
I like the profiles idea

**Comment by konstruktoid** [comment]
I believe this was solved with #283. Closing.
