### ISSUE TITLE
Is it possible to add containers/images filter by LABEL

### ISSUE THREAD

**Issue by lekpamartin** [docker/docker-bench-security#530]
Hi,
For now when we exclude container by name. If another instance are deployed with the others name, we have to update the exclusion list. 
I think LABEL can solve the problem? 
Thx

**Comment by konstruktoid** [comment]
absolutely, are you interested in submitting a PR?

**Comment by lekpamartin** [comment]
https://github.com/docker/docker-bench-security/pull/531

**Comment by konstruktoid** [comment]
Merged  #531
