### ISSUE TITLE
Docker 1.6.0 is the latest version

### ISSUE THREAD

**Issue by anubhav1992** [docker/docker-bench-security#534]
CIS 1.6.0 for Docker (https://www.cisecurity.org/benchmark/docker), Is there any plan to upgrade the code based on the latest version

**Comment by konstruktoid** [comment]
Hi @anubhav1992, there are no actual code changes in the 1.6.0 CIS Benchmark changelog as far as I can tell.
But I'll have a second look and update the documentation

**Comment by konstruktoid** [comment]
1.6.0 released https://github.com/docker/docker-bench-security/releases/tag/v1.6.0
