### ISSUE TITLE
check 5_14 maximum attempts or maximum retry should be <= 5.

### ISSUE THREAD

**Issue by codefrogs** [docker/docker-bench-security#538]
If a container stops restarts for 0-5 times then this is secure. Containers should not fail because the maximum attempts/retries is less then 5. 
See line 614 of 5_container_runtime.sh function check_5_14

**Comment by konstruktoid** [comment]
Hi @codefrogs and thanks for creating this issue, I'll have a look as soon as possible.

**Comment by konstruktoid** [comment]
Yeah, you right. "You should use the on-failure restart policy to limit the number of
container restarts to a _maximum_ of 5 attempts."

**Comment by konstruktoid** [comment]
So sorry for the delay, could you please test https://github.com/docker/docker-bench-security/pull/539?
