### ISSUE TITLE
Docker daemon socket security

### ISSUE THREAD

**Issue by Nethaji-nethu** [docker/docker-bench-security#544]
Please add docker daemon socket security checks. `tcp://0.0.0.0:4243/version` or `unix:///var/run/docker.sock` , if open, could you please add a check to see if there is an authentication mechanism in place ? or atleast warn the user about API being exposed ?
Thanks

**Comment by konstruktoid** [comment]
Hi @Nethaji-nethu, are there any specific situations that aren't caught with the current code?
