### ISSUE TITLE
jq error

### ISSUE THREAD

**Issue by suljov** [docker/docker-bench-security#551]
hello. i get this error when running the script:

```
jq: error: Could not open file /var/snap/docker/2915/config/daemon.json: Permission denied
```

i do get output from the script as usual but on some places i get this error with the output.
i tried running with sudo then after as root still get the same error.

not sure if i missed a step or something.

**Comment by konstruktoid** [comment]
Are you running Docker in as a snap, `/var/snap/docker`? That has never been tested as far as I know.

**Comment by suljov** [comment]
> Hi @suljov. Are you running Docker in as a snap, `/var/snap/docker`? That has never been tested as far as I know.

yes it does run in a snap in the `/ var/snap/docker`

**Comment by konstruktoid** [comment]
I would recommend you to install Docker as per recommendation, see https://github.com/docker-archive/docker-snap: "NOTE: The Docker Snap is no longer maintained by Docker, Inc. The last release version was 17.06.2. The future of the Docker Snap is unclear, but it won't be developed here going forward."
