### ISSUE TITLE
auditctl not found, but on host OS

### ISSUE THREAD

**Issue by phobologic** [docker/docker-bench-security#65]
Not sure how this is supposed to work, but whenever I run it on my host (Ubuntu 14.04) with auditctl installed, it always reports that auditctl was not found.  I'm running it via the docker run command in the README:

```
docker run -it --net host --pid host --cap-add audit_control     -v /var/lib:/var/lib     -v /var/run/docker.sock:/var/run/docker.sock     -v /usr/lib/systemd:/usr/lib/systemd     -v /etc:/etc --label docker_bench_security     diogomonica/docker-bench-security
```

It doesn't list anything about mounting /sbin, so I'm not sure how it is supposed to find auditctl:

```
# which auditctl
/sbin/auditctl
```

**Comment by konstruktoid** [comment]
Hi,
`diogomonica/docker-bench-security`, and the default Dockerfile, uses `FROM alpine:3.2` which (sorry to say) doesn't include `auditctl`. A Debian `Dockerfile` is available https://github.com/docker/docker-bench-security/blob/master/distros/Dockerfile.debian.
I hope that helps.

**Comment by konstruktoid** [comment]
@phobologic, any comments on https://github.com/docker/docker-bench-security/pull/66?

**Comment by phobologic** [comment]
That seems fine - though it might be worth having the shell script actually output something about that itself.  Also - any reason not to create a docker image that actually has all the tools it needs to complete the task?

**Comment by konstruktoid** [comment]
Thanks, I'll merge that README PR and you're absolutely right that the best solution would be a image that has all the tools. Sadly there has been some issues when running, for example, `FROM: debian` on a `CoreOS` host (see https://github.com/docker/docker-bench-security/pull/28). `Alpine`has so far been the most compatible solution.

**Comment by phobologic** [comment]
Ahh - yeah, we used a lot of Alpine at my company for a while, then ran into issues in too many places (the lack of search paths with resolv.conf was brutal for us).  I'm using this tool to bring the AMI for Empire (https://github.com/remind101/empire) up to docker bench standards, so thanks for providing it :)

**Comment by konstruktoid** [comment]
Thanks for using it and helping to improve it.
Closing since #66 was merged.
