### ISSUE TITLE
Add ability to filter out docker-bench-security container from results

### ISSUE THREAD

**Issue by jwilmoth** [docker/docker-bench-security#68]
The Docker container that executes the security benchmark tests shows up in a number of warnings that obscures the work needed to secure the target Docker containers.  It would be nice to exclude the container that is running the tests from the analysis by default (or atleast add an option to exclude).

**Comment by d-a-v-i--** [comment]
confirmed. guess i should fix instead of just tweeting about it?

**Comment by diogomonica** [comment]
@jwilmoth this container should already be excluded. That is why we are using the --label

**Comment by d-a-v-i--** [comment]
warnings i get when running are all for the docker-bench-security container itself

**Comment by diogomonica** [comment]
@d-a-v-i-- confirmed locally. We have a regression somewhere. /cc @konstruktoid

**Comment by d-a-v-i--** [comment]
as mentioned Aug 1: https://twitter.com/daviottenheimer/status/627526813820960768

**Comment by konstruktoid** [comment]
Sorry for the late reply, I merged #69 which should fix this issue.

**Comment by konstruktoid** [comment]
Please reopen if #69 didn't fix.
