### ISSUE TITLE
command line options checks are for short or long versions of options only

### ISSUE THREAD

**Issue by andreasstieger** [docker/docker-bench-security#97]
Only the short or long variants of various docker daemon command line options are checked for, giving incorrect results. The following are not accounted for (not necessarily exhaustive)

tests/2_docker_daemon_configuration.sh
* 2.3: -l, --log-level, only long version checked
* 2.8, 2.9, 2.10: -H, --host=[], only short checked

**Comment by konstruktoid** [comment]
Thanks for reporting this @andreasstieger.
