### ISSUE TITLE
tests do not account for command line switched used multiple times

### ISSUE THREAD

**Issue by andreasstieger** [docker/docker-bench-security#98]
Connected to #97: some checks are against non-cumulative options that can be specified multiple times, overwriting previous setting. e.g.:

    docker daemon --log-level="debug" --log-level="info"

This will run the daemon with info, but the grep in check 2.3 finds a false positive:

    # 2.3
    check_2_3="2.3  - Set the logging level"
    get_command_line_args docker | grep "log-level=\"debug\"" >/dev/null 2>&1

**Comment by andreasstieger** [comment]
Also `docker daemon --icc=true --icc=false`

**Comment by konstruktoid** [comment]
Thanks for reporting this issue @andreasstieger.

**Comment by konstruktoid** [comment]
Closed thanks to #100
