### ISSUE TITLE
command line options tests check for specific quotation of options

### ISSUE THREAD

**Issue by andreasstieger** [docker/docker-bench-security#99]
Connected to #97, #98: A specific use of quotation marks of the command line options is checked for:

    # 2.3
    check_2_3="2.3  - Set the logging level"
    get_command_line_args docker | grep "log-level=\"debug\"" >/dev/null 2>&1

This misses the following cases of spacing and quotation, all of which enable the debug mode:
* `--log-level=debug`
* `--log-level debug`

**Comment by konstruktoid** [comment]
Thanks for reporting this issue @andreasstieger.

**Comment by konstruktoid** [comment]
Closed thanks to #100
